dodaj info o 1pkt za zrobienie na prawdziwym obrazku.
popraw zadania o copy

# Lista 2

## Numpy podstawy

(9pkt + 3pkt)

Na liście znajduje się 9 zadań do wykonania w trakcie zajęć. Po rozwiązaniu zadania pokaż kod prowadzącemu i odpowiedz na **pytanie kontrolne** (są one podane przy każdym zadaniu) — wtedy przyznajemy punkt. Dodatkowo prześlij zadanie na platformie skos.

Jeśli w poleceniu nie jest wskazane użycie pętli `for` - nie korzystaj z niej.

Zadania dodatkowe są oznaczone ⭐️. To zadani o numerach 10 i 11. Dodatkowo moeżesz otrzymać 1pkt z puli punktów bonusowych jeśli wykonasz wszystkie poniższe zadania związane z obrazami na prawdziwym obrazku.

Kazde zadnanie warte jest 1pkt.

## 1. Analiza pikseli obrazu

**Kontekst:** W AI obrazy to tablice NumPy (np. `H×W×C`). Proste operacje na obrazach można robić wektorowo bez pętli.

**Polecenie**

* Utwórz przykładową tablicę 3×3 obrazu RGB zawierającą wartości 0–255.
* Zwiększ jasność o 10% — ale **nie przekraczaj 255** (`np.clip`).
* Pokaż wynik i typ danych.

**Podpowiedź**
Zwiększ jasność obrazu mnożąc każde pasmo RGB przez 110%.

In [ ]:
import numpy as np

A = np.random.randint(0, 256, (3, 3)) # Uzupełnij
bright = np.clip(A*1.1, 0, 255).astype(np.int64) # Uzupełnij

print("Oryginał:\n", A)
print("Po zwiększeniu jasności o 10%:\n", bright)

Oryginał:
 [[  5 196 159]
 [243 108 221]
 [ 88 113 240]]
Po zwiększeniu jasności o 10%:
 [[  5 215 174]
 [255 118 243]
 [ 96 124 255]]


## 2. Normalizacja danych wejściowych

**Kontekst:** Dane wejściowe do modeli zazwyczaj normujemy — albo do `[0,1]`, albo standaryzujemy do średniej 0 i odchylenia 1.

**Polecenie**

* Wygeneruj 1D tablicę 100 losowych liczb w przedziale `0..255`.
* Przeskaluj na `[0,1]`.
* Następnie stwórz znormalizowaną wersję z średnią 0 i odchyleniem 1 (standaryzacja).
* Nie używaj pętli.

**Pytanie kontrolne:** Co się stanie, gdy `std == 0`?

In [ ]:
import numpy as np

x = np.random.randint(0, 256, 100)

# skalowanie do [0,1]
x_scaled = np.clip(x/255, 0, 1)

# standaryzacja: (x - mean)/std
mean = np.mean(x_scaled)
std = np.std(x_scaled)
# gdy std == 0 to mamy dzielenie przez 0, co w wyniku daje +-inf
x_standardized = (x_scaled - mean)/std

print("mean scaled:", mean)
print("mean standardized:", std)
print("std standardized:", x_standardized)

mean scaled: 0.5123921568627451
mean standardized: 0.2985528185549888
std standardized: [ 1.09469249  0.89766361 -1.09889578 -0.87559637 -0.08748083 -1.25651889
  1.5412913  -0.98067844  0.92393413 -0.7705143   0.30657695  0.63495843
  0.35911798  0.72690524  1.47561501 -0.28450971  0.47733532  0.70063472
 -1.24338363 -1.41414199  1.40993871  0.31971221 -1.65057666  0.18835962
  0.35911798  0.80571679  0.75317576 -1.16457207  0.28030643  1.48875027
  1.40993871  0.52987635  0.01760125 -0.88873163 -1.66371192 -0.36332127
 -1.5717651   1.47561501 -1.20397785  1.10782775  0.41165902 -0.45526808
 -0.08748083 -0.73110852  0.83198731  0.87139309  1.35739768 -0.62602645
 -0.91500215 -1.62430614  1.37053293  0.05700702  0.85825783 -1.11203104
 -1.37473622 -0.67856749 -1.26965414  0.12268332  1.48875027  0.17522436
  1.06842198 -0.29764497  0.6743642   0.59555265 -1.32219518 -0.20569816
 -0.75737904  0.00446599  0.87139309 -0.04807505 -1.53235933 -1.53235933
  0.72690524 -0.98067844 -0.92813741

## 3. Wycinanie fragmentów danych

**Kontekst:** Często dzielimy długi sygnał na krótsze okna (np. do ekstrakcji cech).

**Polecenie**

* Stwórz 1D tablicę długości 1000 (np. `np.arange(1000)`).
* Podziel ją na 10 fragmentów po 100 elementów (`reshape`).
* Oblicz średnią każdego fragmentu (wektor 10-elementowy).

**Pytanie kontrolne:** Co policzymy jeśli obliczymy `axis=0`?

In [ ]:
import numpy as np

x = np.arange(1000)
chunks = x.reshape(10, 100)
means = np.mean(chunks, axis=1)

print("shape chunks:", chunks.shape)
print("means:", means)

shape chunks: (10, 100)
means: [ 49.5 149.5 249.5 349.5 449.5 549.5 649.5 749.5 849.5 949.5]


## 4. Operacje wzdłuż osi

**Kontekst:** Przy normalizacjach i agregacjach często operujemy wzdłuż konkretnej osi.

**Polecenie**

* Utwórz `X = np.random.randint(0, 100, (5,4))`.
* Oblicz:

  * min każdego wiersza używając `X.min(...)`
  * max każdej kolumny używając `X.max(...)`
* Znormalizuj każdy wiersz tak, aby suma elementów w wierszu była równa 1. Sprawdź poprawność rozwiązania sumując wartości w każdym wierszu.

In [ ]:
import numpy as np

X = np.random.randint(0, 100, (5,4))

row_mins = X.min(axis=1)
col_maxs = X.max(axis=0)

# normalizacja wierszy do sumy 1
row_sums = X.sum(axis=1).reshape(5, 1)    # shape (5,1) - jakiego parametru trzeba użyć?
X_norm = X / row_sums

print("X:\n", X)
print("row_mins:", row_mins)
print("col_maxs:", col_maxs)
print("X_norm (suma wiersza):", X_norm.sum(axis=1))

X:
 [[24 46  7 12]
 [ 6 74 91 68]
 [37 74 76 85]
 [39 13 78 73]
 [20 93  0 48]]
row_mins: [ 7  6 37 13  0]
col_maxs: [39 93 91 85]
X_norm (suma wiersza): [1. 1. 1. 1. 1.]


## 5. Analiza embeddingów słów

**Kontekst:** W NLP słowa reprezentujemy wektorami (embeddingi). Często chcemy średnią reprezentację zdania i podobieństwo kosinusowe.

**Polecenie**

* Stwórz macierz `E` o kształcie `(5,50)` — 5 embeddingów po 50 wymiarów (`np.random.randn`).
* Oblicz:

  * `mean_embedding` (średni wektor po wierszach)
  * macierz podobieństw kosinusowych między wszystkimi parami wektorów (5×5)

**Pytanie kontrolne:** Jak interpretujesz wartości w `cosine_sim` (zakres i znaczenie)?

---

### Wskazówka

Zastanów się, jak można obliczyć **podobieństwo kosinusowe** dwóch wektorów `a` i `b`, jeśli wiesz, że:

$$
\cos(\theta) = \frac{a \cdot b}{|a| \cdot |b|}
$$

Spróbuj najpierw policzyć to dla jednej pary wektorów w NumPy,
używając `np.dot()` i `np.linalg.norm()`.

A następnie pomyśl:

* Jak znormalizować wszystkie wektory jednocześnie, żeby każdy miał długość 1?
* Jak wykorzystać mnożenie macierzy (`@`), żeby w jednym kroku dostać podobieństwa między wszystkimi parami wektorów (5×5)?

In [ ]:
# cosine sim to cosinusowe podobieństwo między każdą parą wektorów
# dlatego na przekątnej mamy 1 - wektor jest identyczny ze sobą

import numpy as np

E = np.random.randn(5, 50)

# średni wektor (embedding zdania)
mean_embedding = np.mean(E, axis=0)

a = E[0]
b = E[1]
print(np.dot(a, b) / (np.linalg.norm(a) * np.linalg.norm(b)))

# normalizacja wektorów do długości 1
norms = np.linalg.norm(E, axis=1).reshape(5, 1)
E_normalized = E / norms

# macierz podobieństw kosinusowych = E_norm @ E_norm.T
cosine_sim = E_normalized @ E_normalized.T

print("mean_embedding shape:", mean_embedding.shape)
print("cosine_sim shape:", cosine_sim.shape)
print("cosine_sim (przykład):\n", cosine_sim)

-0.13910853531887638
mean_embedding shape: (50,)
cosine_sim shape: (5, 5)
cosine_sim (przykład):
 [[ 1.         -0.13910854 -0.23545391 -0.14678445 -0.08550306]
 [-0.13910854  1.          0.14122223 -0.14158484  0.06081683]
 [-0.23545391  0.14122223  1.          0.02608373  0.04997289]
 [-0.14678445 -0.14158484  0.02608373  1.          0.01588249]
 [-0.08550306  0.06081683  0.04997289  0.01588249  1.        ]]


## 6. Sklejanie sensorów — dane z pojazdu autonomicznego

**Kontekst:** Dane z różnych sensorów różnią się formatem — trzeba je połączyć w jedną macierz cech.

**Polecenie**

* Stwórz:

  ```python
  lidar = np.random.rand(100, 2)   # x,y # lidar - Light Detection and Ranging
  camera = np.random.rand(100, 1)  # jasność
  radar = np.random.rand(100, 1)   # prędkość
  ```
* Połącz je kolumnowo w macierz `X` o kształcie `(100,4)`.
* Podziel `X` na `train` (80%) i `test` (20%) (np. `np.array_split` lub indeksowanie).
* Oblicz średnią jasność i średnią prędkość dla obu zestawów.

**Pytanie kontrolne:** Dlaczego warto przetasować dane (shuffle) przed splitem w prawdziwym pipeline?

In [ ]:
# normalnie tasujemy dane, bo nie wiemy w jakim rozkładzie są one w datasecie
# np możemy najpierw mieć pozytywne, później negatywne próbki, więc testujemy tylko na negatywnych

import numpy as np

lidar = np.random.rand(100, 2)   # x,y
camera = np.random.rand(100, 1)  # jasność
radar = np.random.rand(100, 1)   # prędkość

X = np.hstack((lidar, camera, radar))
assert X.shape == (100, 4)

# split train/test (bez shuffle dla prostoty)
n_train = np.floor(0.8*len(X)).astype(np.int32)
train, test = np.vsplit(X, (n_train,))

# indeksy kolumn: camera -> 2, radar -> 3 (0-based)
mean_camera_train = np.mean(train[:, 2])
mean_radar_train = np.mean(train[:, 3])
mean_camera_test = np.mean(test[:, 2])
mean_radar_test = np.mean(test[:, 3])

print("X.shape:", X.shape)
print("train/test shapes:", train.shape, test.shape)
print("mean camera train/test:", mean_camera_train, mean_camera_test)
print("mean radar train/test:", mean_radar_train, mean_radar_test)

X.shape: (100, 4)
train/test shapes: (80, 4) (20, 4)
mean camera train/test: 0.5280871093572775 0.6106467803774331
mean radar train/test: 0.5426740790312261 0.574587972350673


## 7. NumPy vs. czysty Python

**Kontekst:** NumPy działa o wiele szybciej niż pętle Pythonowe dla operacji numerycznych. Tu wykorzystamy `np.linspace`.

**Polecenie**

* Stwórz `x = np.linspace(0, 1, 10_000_000)`.
* Oblicz `s = sin(x)**2 + cos(x)**2`:

  * a) w czystym Pythonie (pętla `for` i `math.sin`, `math.cos`)
  * b) w NumPy (`np.sin`, `np.cos` — wektoryzacja)
* Porównaj czasy wykonania (wskazane: `%timeit` w notebooku lub `time.time()`).

In [ ]:
import numpy as np
import math
import time

# dane
x = np.linspace(0, 1, 10_000_000)

# NumPy version
t0 = time.time()
y_np = np.sin(x)**2 + np.cos(x)**2
t_np = time.time() - t0

# Python loop version (bardzo wolne; uruchamiaj ostrożnie; jak trwa dłuej ni 15s, to przerwij i zmniejsz przykład)
t0 = time.time()
s = 0.0
for xi in x:
    s += math.sin(xi)**2 + math.cos(xi)**2
t_py = time.time() - t0

print(f"NumPy time: {t_np:.3f}s")
print(f"Pure Python loop time: {t_py:.3f}s")

NumPy time: 0.313s
Pure Python loop time: 5.643s


## 8. Copy, View

**Kontekst:** Podczas preprocessingu zespoły czasami pracują na tym samym obiekcie myśląc, że mają kopię — to prowadzi do skażenia danych.

**Polecenie**

* Stwórz `patients = np.random.randint(60, 120, (5, 4))`.
  * `doctors_view`, gdzie doktor będzie przeglądał tylko co drugi pomiar,
  * `research_copy`, czyli kopię patients.
* Lekarz przez pomyłkę wykona `doctors_view[:] = -1`.
* Sprawdź, czy `patients` się zmieniło i czy `research_copy` pozostało bez zmian. Wyjaśnij.

**Pytanie kontrolne:** W jaki sposób zabezpieczyć workflow, żeby przypadkowe zmiany nie wpływały na bazę danych?

In [ ]:
# aby zabezpieczyć bazę danych powinniśmy zawsze pracować na kopii danych

import numpy as np

patients = np.random.randint(60, 120, (5, 4))
doctors_view = patients.view()
research_copy = patients.copy()

print("przed zmiana:\n", patients)
doctors_view[:] = -1
print("po zmianie doctors_view:\n", patients)
print("research_copy (czy zmienione?):\n", research_copy)

# wykrywamy, które są view / copy
print("doctors_view.base is patients?", doctors_view.base is patients)
print("research_copy.base is patients?", research_copy.base is patients)

przed zmiana:
 [[ 74 114 117  89]
 [ 90  89  98 119]
 [116  98  92 104]
 [ 68 117  73  92]
 [ 61  88  93  68]]
po zmianie doctors_view:
 [[-1 -1 -1 -1]
 [-1 -1 -1 -1]
 [-1 -1 -1 -1]
 [-1 -1 -1 -1]
 [-1 -1 -1 -1]]
research_copy (czy zmienione?):
 [[ 74 114 117  89]
 [ 90  89  98 119]
 [116  98  92 104]
 [ 68 117  73  92]
 [ 61  88  93  68]]
doctors_view.base is patients? True
research_copy.base is patients? False


## 9. Jak CNN „przesuwa okno” po obrazie?

**Kontekst:** W konwolucyjnej sieci neuronowej filtr (np. 3×3) „przesuwa się” po obrazie piksel po pikselu. Parametr stride określa, o ile pikseli filtr przesuwa się w pamięci między kolejnymi pozycjami. Zrozumienie, jak numpy.strides działa, pozwala intuicyjnie pojąć, dlaczego operacja konwolucji może być wydajna bez kopiowania danych.

**Polecenie**

1. Utwórz: `A = np.arange(1,13).reshape(3,4)` — traktuj jako obraz `3 × 4`, oraz `AT = A.T`.
2. Wypisz: `A`, `A.strides`, `AT`, `AT.strides`.
3. Oblicz ile bajtów trzeba przeskoczyć, aby dotrzeć:
   * od `A[0,0]` do `A[0,1]`,
   * od `A[0,0]` do `A[1,0]`.
4. Sprawdź, czy `AT` jest widokiem (`AT.base is A`), zmień `A[0,0] = -99` i sprawdź `AT`.
5. Napisz funkcję `memory_offset(A, i, j)`, która obliczy ile bajtów trzeba przejść od `A[0][0]` do miejsca `A[i][j]`
   Użyj jej, żeby policzyć offsety kilku elementów w `A` i `A.T`. Zinterpretuj wyniki.

**Pytanie kontrolne:** Wyjaśnij własnymi słowami: co się stanie jak zmienisz `strides`?

In [ ]:
# jeżeli zmienimy strides zmieniamy to jak numpy widzi dane
# zmienimy sposób w jaki numpy porusza się po danych

import numpy as np
import sys

A = np.arange(1, 13).reshape(3, 4)
print("A:\n", A)
print("A.strides:", A.strides)

AT = A.T
print("AT:\n", AT)
print("AT.strides:", AT.strides)

# elementsize (liczba bajtów na element)
bs = sys.getsizeof(A[0][0])
print("itemsize (bajtów per element):", bs)

# obliczenia ręczne:
offset_A_00_to_01 = A.strides[1] * bs
offset_A_00_to_10 = A.strides[0] * bs
print("offset A[0,0] -> A[0,1] (bajtów):", offset_A_00_to_01)
print("offset A[0,0] -> A[1,0] (bajtów):", offset_A_00_to_10)

# sprawdzenie widoku
print("A.T.base is A ?", AT.base is A)

# zmiana A i obserwacja AT
A[0,0] = -99
print("A po zmianie:\n", A)
print("A.T po zmianie:\n", AT)

# funkcja memory_offset
def memory_offset(M, i, j):
    return (M.strides[0]*i + M.strides[1]*j) * bs

print("memory offset A[2,3]:", memory_offset(A, 2, 3))
print("memory offset AT[2,3]:", memory_offset(AT, 2, 3))

print("memory offset A[0,1]:", memory_offset(A, 0, 1))
print("memory offset A[1,0]:", memory_offset(A, 1, 0))

A:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
A.strides: (32, 8)
AT:
 [[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]
AT.strides: (8, 32)
itemsize (bajtów per element): 32
offset A[0,0] -> A[0,1] (bajtów): 256
offset A[0,0] -> A[1,0] (bajtów): 1024
A.T.base is A ? False
A po zmianie:
 [[-99   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]
A.T po zmianie:
 [[-99   5   9]
 [  2   6  10]
 [  3   7  11]
 [  4   8  12]]
memory offset A[2,3]: 2816
memory offset AT[2,3]: 3584
memory offset A[0,1]: 256
memory offset AT[1,0]: 1024


## 10. ⭐️ Zaawansowana augmentacja i analiza obrazów RGB

**Kontekst:** Przy trenowaniu CNN operujemy na obrazach RGB. Często robimy augmentacje (jasność, kontrast, rotacje, przesunięcia) i porównujemy obrazy np. za pomocą **cosine similarity**. Trzeba uważać, które operacje zwracają **widok**, a które **kopię**, aby nie psuć danych przez przypadek.

**Polecenie**

1. Wygeneruj **10 losowych obrazów RGB**, każdy o wymiarach `32×32×3` z wartościami `uint8` (0–255).
2. Napisz funkcję `cosine_similarity(img1, img2)`, która oblicza podobieństwo kosinusowe między dwoma obrazami traktowanymi jako wektory.
3. Stwórz funkcję `augment(img)` która tworzy warianty obrazu:

   * oryginał,
   * flip poziomy,
   * flip pionowy,
   * rotacja 90°,
   * jaśniejsza wersja,
   * wersja z większym kontrastem,
   * mały przesunięty fragment (crop + pad),
   * zamiana kanałów RGB na BGR.
4. Dla każdego wariantu sprawdź, które są **widokiem**, a które **kopią** (`.base`).
5. Oblicz macierz podobieństwa kosinusowego między wszystkimi 10 obrazami oryginalnymi i wypisz średnie podobieństwo.
6. Oblicz podobieństwo między oryginałami a ich wariantami i sprawdź, które operacje najbardziej zmieniają obraz (najmniejsze cosine similarity).   

In [ ]:
import numpy as np

def cosine_similarity(img1, img2):
    img1_flat = img1.view().reshape(-1).astype(np.float32)
    img2_flat = img2.view().reshape(-1).astype(np.float32)

    similarity = (np.dot(img1_flat, img2_flat)) / (np.linalg.norm(img1_flat) * np.linalg.norm(img2_flat) + 1e-8)
    return similarity

def contrast(img):
    # return a new array with increased contrast (uint8)
    img = img.astype(np.float32)
    min_val = np.percentile(img, 20)
    max_val = np.percentile(img, 80)
    img = np.clip(img, min_val, max_val)
    img = ((img - min_val) / (max_val - min_val + 1e-8)) * 255
    return np.clip(img, 0, 255).astype(np.uint8)


def augment(img):
    cropped_img = img[10:20, 10:20]
    padded_cropped_img = np.pad(cropped_img, (
        (0, 32 - cropped_img.shape[0]),
        (0, 32 - cropped_img.shape[1]),
        (0, 0)), mode='constant')

    return [
        img,    # original
        np.flip(img, axis=0),   # row-wise flip
        np.flip(img, axis=1),   # column-wise flip
        np.rot90(img),          # rotation 90
        np.clip(img.astype(np.float32)*1.5, 0, 255).astype(np.uint8),   # brightness
        contrast(img), # contrast
        padded_cropped_img,  # crop
        img[:, :, [2, 1, 0]]   # BGR
    ]


imgs = np.random.randint(0, 256, (10, 32, 32, 3), dtype=np.uint8)
augmented_imgs = [augment(imgs[idx]) for idx in range(len(imgs))]

for aug_img in augmented_imgs[0]:
    print(aug_img.base is imgs[0])

similarities = np.zeros((10, 10))
for i in range(10):
    for j in range(10):
        similarities[i, j] = cosine_similarity(imgs[i], imgs[j])

print(np.round(similarities, 2))
print("AVG similarity:", np.mean(similarities))


names = ["original", "flip_row", "flip_col", "rot90", "brightness", "contrast", "crop", "bgr"]
for name in names: print(name, end=", ")
print()

for i in range(len(imgs)):
    original_img = imgs[i]
    for aug_img in augmented_imgs[i]:
        print(np.round(cosine_similarity(original_img, aug_img), 2), end=", ")
    print()

False
False
False
False
False
False
False
False
[[1.   0.76 0.75 0.74 0.75 0.76 0.74 0.75 0.76 0.76]
 [0.76 1.   0.74 0.74 0.74 0.74 0.75 0.76 0.75 0.75]
 [0.75 0.74 1.   0.74 0.75 0.76 0.75 0.75 0.75 0.75]
 [0.74 0.74 0.74 1.   0.76 0.76 0.75 0.76 0.75 0.75]
 [0.75 0.74 0.75 0.76 1.   0.75 0.75 0.75 0.76 0.75]
 [0.76 0.74 0.76 0.76 0.75 1.   0.76 0.75 0.75 0.75]
 [0.74 0.75 0.75 0.75 0.75 0.76 1.   0.75 0.76 0.74]
 [0.75 0.76 0.75 0.76 0.75 0.75 0.75 1.   0.76 0.76]
 [0.76 0.75 0.75 0.75 0.76 0.75 0.76 0.76 1.   0.76]
 [0.76 0.75 0.75 0.75 0.75 0.75 0.74 0.76 0.76 1.  ]]
AVG similarity: 0.7757553297281266
original, flip_row, flip_col, rot90, brightness, contrast, crop, bgr, 
1.0, 0.75, 0.76, 0.75, 0.99, 0.99, 0.25, 0.84, 
1.0, 0.75, 0.75, 0.75, 0.99, 0.99, 0.23, 0.84, 
1.0, 0.74, 0.74, 0.74, 0.99, 0.99, 0.22, 0.83, 
1.0, 0.74, 0.74, 0.74, 0.99, 0.99, 0.22, 0.82, 
1.0, 0.74, 0.75, 0.75, 0.99, 0.99, 0.24, 0.83, 
1.0, 0.75, 0.75, 0.75, 0.99, 0.99, 0.24, 0.84, 
1.0, 0.75, 0.75, 0.74, 0.99

## 11. ⭐️ Świadome kopiowanie

**Kontekst**
Pracujesz z dużymi macierzami w Pythonie/NumPy, które reprezentują np. wyniki eksperymentów, symulacje lub dane użytkowników.

**Polecenie**
Twoim zadaniem jest zdecydować w jaki sposób należy **modyfikować dane**, w miejscu, w kopii, czy wystarczy widok? A może trzeba użyć deepcopy? Rozważ dwa przypadki - kiedy używasz biblioteki `numpy` i `copy`. Odpowiedz na wszystkie pytania. W każdej części musisz **uzasadnić wybór metody**.

Na początku stwórz dwuwymiarową tablicę `M`, na której będziesz demonstrować i uzasadniać użycie wybranej metody.

#### **a) Lokalna korekta**

Wartość w komórce `[0,0]` jest błędna i powinna być `1`.

* Jak poprawisz tę wartość?
* Czy zmieniasz oryginał, czy tworzysz kopię?
* Jak działa pamięć w tym przypadku?

#### **b) Alternatywna wersja danych**

Chcesz stworzyć **zmodyfikowaną wersję danych**, np. w kolumnie 2 przeskalować wszystkie wartości, w celu przeprowadzenia eksperymentu.

* Zastanów się, czy potrzebujesz `view`, `copy` czy `deepcopy`.
* Przetestuj różne podejścia (`M.view()`, `M.copy()`) i sprawdź, co się dzieje po modyfikacji nowej macierzy.

#### **c) Symulacje z listą zagnieżdżoną**

Tworzysz listę eksperymentów:

```python
L = [M, M.copy()]
```

Teraz chcesz **przeprowadzić symulacje zmian**, np. dodając losowe wartości, **bez zmiany oryginału** ani kopii w `L`.

* Jakiego rodzaju kopiowania użyjesz?
* Co się stanie, jeśli użyjesz tylko `copy` zamiast `deepcopy`, gdy struktura jest zagnieżdżona?

#### **d) Podzbiór kolumn**

Wybierasz podzbiór kolumn np. 1 i 3:

```python
subset = M[:, [1, 3]]
```

* Sprawdź, czy zmiany w `subset` wpływają na `M`.
* Porównaj to z cięciem typu `subset = M[:, 1:3]`.

In [16]:
import numpy as np
import copy

M = np.random.randint(0, 10, (4,4))

# #### **a) Lokalna korekta**

# Wartość w komórce `[0,0]` jest błędna i powinna być `1`.

# * Jak poprawisz tę wartość?
# * Czy zmieniasz oryginał, czy tworzysz kopię?
# * Jak działa pamięć w tym przypadku?

# nie robimy kopii, bo wartość jest błędna i chcemy ją poprawić w oryginale
M[0, 0] = 1


# #### **b) Alternatywna wersja danych**

# Chcesz stworzyć **zmodyfikowaną wersję danych**, np. w kolumnie 2 przeskalować wszystkie wartości, w celu przeprowadzenia eksperymentu.

# * Zastanów się, czy potrzebujesz `view`, `copy` czy `deepcopy`.
# * Przetestuj różne podejścia (`M.view()`, `M.copy()`) i sprawdź, co się dzieje po modyfikacji nowej macierzy.

# chcemy stworzyć nową wersję, wię chcemy zachować oryginalne dane, więc tworzymy kopię wszystkich danych 
M2 = M.copy()
M2_copy = copy.deepcopy(M)

M2[:, 1] = M2[:, 1] * 10  # skalowanie kolumny 2
M2_copy[:, 1] = M2_copy[:, 1] * 20  # skalowanie kolumny 2 jeszcze inaczej

print("M przed zmianą:\n", M)
print("M2 po zmianie:\n", M2)
M2_view = M.view()
M2_view[:, 1] = M2_view[:, 1] * 30
print("M2_view po zmianie:\n", M2_view)

# #### **c) Symulacje z listą zagnieżdżoną**

# Tworzysz listę eksperymentów:

# ```python
# L = [M, M.copy()]
# ```

# Teraz chcesz **przeprowadzić symulacje zmian**, np. dodając losowe wartości, **bez zmiany oryginału** ani kopii w `L`.

# * Jakiego rodzaju kopiowania użyjesz?
# * Co się stanie, jeśli użyjesz tylko `copy` zamiast `deepcopy`, gdy struktura jest zagnieżdżona?

# chcemy stworzyć pełną kopię L, więc skorzystamy z biblioteki copy (bo L nie jest numpy'owe)
# użycie zwykłego copy spowoduje, że wewnętrzne macierze nadal będą referencjami do oryginału lub jego kopii
L = [M, M.copy()]
L_copy = copy.deepcopy(L)
L_ref = copy.copy(L)
print("L przed zmianą:\n", L)
L_copy[0][0,0] = -100
L_ref[1][0,0] = -200
print("L_copy po zmianie:\n", L_copy)
print("L_ref po zmianie:\n", L_ref)

# #### **d) Podzbiór kolumn**

# Wybierasz podzbiór kolumn np. 1 i 3:

# ```python
# subset = M[:, [1, 3]]
# ```

# * Sprawdź, czy zmiany w `subset` wpływają na `M`.
# * Porównaj to z cięciem typu `subset = M[:, 1:3]`.


subset = M[:, [1, 3]]
subset_slice = M[:, 1:3]

print("M przed zmianą subset:\n", M)
subset[:, 0] = -50
print("M po zmianie subset:\n", M)
subset_slice[:, 0] = -75
print("M po zmianie subset_slice:\n", M)



M przed zmianą:
 [[1 1 1 4]
 [7 3 1 6]
 [1 0 6 0]
 [1 4 3 7]]
M2 po zmianie:
 [[ 1 10  1  4]
 [ 7 30  1  6]
 [ 1  0  6  0]
 [ 1 40  3  7]]
M2_view po zmianie:
 [[  1  30   1   4]
 [  7  90   1   6]
 [  1   0   6   0]
 [  1 120   3   7]]
L przed zmianą:
 [array([[  1,  30,   1,   4],
       [  7,  90,   1,   6],
       [  1,   0,   6,   0],
       [  1, 120,   3,   7]]), array([[  1,  30,   1,   4],
       [  7,  90,   1,   6],
       [  1,   0,   6,   0],
       [  1, 120,   3,   7]])]
L_copy po zmianie:
 [array([[-100,   30,    1,    4],
       [   7,   90,    1,    6],
       [   1,    0,    6,    0],
       [   1,  120,    3,    7]]), array([[  1,  30,   1,   4],
       [  7,  90,   1,   6],
       [  1,   0,   6,   0],
       [  1, 120,   3,   7]])]
L_ref po zmianie:
 [array([[  1,  30,   1,   4],
       [  7,  90,   1,   6],
       [  1,   0,   6,   0],
       [  1, 120,   3,   7]]), array([[-200,   30,    1,    4],
       [   7,   90,    1,    6],
       [   1,    0,    6,    0],