In [1]:
import numpy as np

# Basic NumPy

## Slicing

**Key Principles**

1. **Syntax:** `array[start:stop:step]`

   * Selects elements starting from `start` (inclusive) to `stop` (exclusive), every `step`.
   * Negative indices count from the end; negative steps reverse order.
   * `::` means “take everything”.

2. **View vs Copy:**
   NumPy slicing returns a **view**, not a copy. Changes to the slice affect the original array.
   Use `.copy()` if you want an independent dataset.

3. **Multidimensional slicing:**
   You can slice along each axis using commas: `data[1:3, ::-1]`.


### Example 1 – Temperature Readings (1D Array)

Imagine you collected hourly temperatures for 10 hours:

In [2]:
import numpy as np

temps = np.array([14, 15, 15, 16, 17, 17, 18, 18, 17, 16])

print("All hourly temperatures:", temps)
print("Every second hour:", temps[::2])
print("Last 3 hours:", temps[-3:])
print("Reversed order (most recent first):", temps[::-1])

All hourly temperatures: [14 15 15 16 17 17 18 18 17 16]
Every second hour: [14 15 17 18 17]
Last 3 hours: [18 17 16]
Reversed order (most recent first): [16 17 18 18 17 17 16 15 15 14]


### Example 2 – Model Predictions (2D Array)

Suppose you have predictions from a regression model over several days for 3 cities:

In [3]:
import numpy as np

preds = np.array([
    [22.3, 21.9, 20.5],
    [23.1, 22.2, 21.0],
    [24.5, 23.8, 22.3],
    [25.0, 24.1, 22.8]
])
# Rows = days, Columns = cities (A, B, C)

print("Full prediction table:\n", preds)
print("\nFirst two days (all cities):\n", preds[:2, :])
print("\nCity C predictions only:\n", preds[:, 2])
print("\nEvery second day (all cities):\n", preds[::2, :])

Full prediction table:
 [[22.3 21.9 20.5]
 [23.1 22.2 21. ]
 [24.5 23.8 22.3]
 [25.  24.1 22.8]]

First two days (all cities):
 [[22.3 21.9 20.5]
 [23.1 22.2 21. ]]

City C predictions only:
 [20.5 21.  22.3 22.8]

Every second day (all cities):
 [[22.3 21.9 20.5]
 [24.5 23.8 22.3]]


### Example 3 – Image Dataset (3D Array)

Now consider you have grayscale images represented as arrays:
Each image has shape `(height, width) = (4, 4)` and there are 2 images total.

In [4]:
import numpy as np

images = np.arange(32).reshape(2, 4, 4)
# Shape: (2 images, 4 rows, 4 columns)

print("Original images:\n", images)
print("\nTop-left 2x2 crop from each image:\n", images[:, :2, :2])
print("\nEvery second row and column:\n", images[:, ::2, ::2])
print("\nHorizontally flipped images:\n", images[:, :, ::-1])

Original images:
 [[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]
  [12 13 14 15]]

 [[16 17 18 19]
  [20 21 22 23]
  [24 25 26 27]
  [28 29 30 31]]]

Top-left 2x2 crop from each image:
 [[[ 0  1]
  [ 4  5]]

 [[16 17]
  [20 21]]]

Every second row and column:
 [[[ 0  2]
  [ 8 10]]

 [[16 18]
  [24 26]]]

Horizontally flipped images:
 [[[ 3  2  1  0]
  [ 7  6  5  4]
  [11 10  9  8]
  [15 14 13 12]]

 [[19 18 17 16]
  [23 22 21 20]
  [27 26 25 24]
  [31 30 29 28]]]


## Understanding "axis" in NumPy

Many NumPy functions (sum, mean, max, min, etc.) take an "axis" argument.

Setting **axis = 0** means: collapse axis 0.
- In a 2D array, axis 0 is the rows.
- So we aggregate *down* the rows, producing one result per column.

Setting **axis = 1** means: collapse axis 1.
- In a 2D array, axis 1 is the columns.
- So we aggregate *across* the columns, producing one result per row.

So when we set axis = 0, we’re not summing across the rows —
we’re aggregating *down* the rows (we collapse axis 0).
When we set axis = 1, we collapse the columns (axis 1).

![axis0](./Images/numpy-axes-np-sum-axis-0.png)
![axis1](./Images//numpy-axes-np-sum-axis-1.png)

### Example - Daily Sales in 3 Stores

In [5]:
import numpy as np

# Rows = days, Columns = stores (A, B, C)
sales = np.array([
    [120, 100, 90],
    [150, 130, 100],
    [170, 160, 110],
    [200, 180, 120]
])

print("Daily sales data:\n", sales)

# When we set axis = 0, we collapse axis 0 (rows).
# So we aggregate *down* the rows — one result per column (store).
print("\nSum per store (axis=0):", np.sum(sales, axis=0))
print("Mean per store (axis=0):", np.mean(sales, axis=0))
print("Max per store (axis=0):", np.max(sales, axis=0))
print("Store index with max total sales (argmax over axis=0):", np.argmax(sales, axis=0))

# When we set axis = 1, we collapse axis 1 (columns).
# So we aggregate *across* the columns — one result per row (day).
print("\nSum per day (axis=1):", np.sum(sales, axis=1))
print("Mean per day (axis=1):", np.mean(sales, axis=1))
print("Min per day (axis=1):", np.min(sales, axis=1))
print("Column index of min sale each day (argmin over axis=1):", np.argmin(sales, axis=1))

Daily sales data:
 [[120 100  90]
 [150 130 100]
 [170 160 110]
 [200 180 120]]

Sum per store (axis=0): [640 570 420]
Mean per store (axis=0): [160.  142.5 105. ]
Max per store (axis=0): [200 180 120]
Store index with max total sales (argmax over axis=0): [3 3 3]

Sum per day (axis=1): [310 380 440 500]
Mean per day (axis=1): [103.33333333 126.66666667 146.66666667 166.66666667]
Min per day (axis=1): [ 90 100 110 120]
Column index of min sale each day (argmin over axis=1): [2 2 2 2]


## Array Combination and Splitting

In data analysis, arrays often need to be **combined** (merged).
NumPy provides intuitive functions for this: `concatenate`, `stack`.

### `np.concatenate()`

Joins existing arrays along an existing axis (must have compatible shapes).

In [6]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])

# Combine along rows (axis=0)
result = np.concatenate((a, b))
print("Concatenate along rows:\n", result)

Concatenate along rows:
 [[1 2]
 [3 4]
 [5 6]]


### `np.stack()`

Creates a **new axis** while joining arrays.
All arrays must have the **same shape**.

In [7]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

stacked0 = np.stack((a, b), axis=0)  # new axis 0
stacked1 = np.stack((a, b), axis=1)  # new axis 1

print("Stacked along new axis 0:\n", stacked0)
print("\nStacked along new axis 1:\n", stacked1)

Stacked along new axis 0:
 [[1 2 3]
 [4 5 6]]

Stacked along new axis 1:
 [[1 4]
 [2 5]
 [3 6]]


**Difference `stack` vs. `concatenate`:**

* `concatenate` merges *existing axes*
* `stack` creates a *new axis*

https://medium.com/better-programming/numpy-illustrated-the-visual-guide-to-numpy-3b1d4976de1d

## NumPy Sorting & Uniqueness Functions

### `np.sort()` – Sort Values

Returns a sorted copy of an array along a given axis.

* By default, sorts along the last axis (`axis = -1`).
* Does **not** modify the original array (use `.sort()` method for in-place sorting).
* Works on multidimensional arrays — you can choose which axis to sort.

#### Example – Sorting model predictions

In [8]:
import numpy as np

# Suppose we have predicted probabilities for 3 classes
probs = np.array([0.65, 0.15, 0.20])

print("Original probabilities:", probs)
print("Sorted probabilities:", np.sort(probs))

Original probabilities: [0.65 0.15 0.2 ]
Sorted probabilities: [0.15 0.2  0.65]


#### Exaample 2

In [9]:
import numpy as np

# Rows = samples, Columns = class probabilities
probs_2d = np.array([
    [0.65, 0.15, 0.20],
    [0.10, 0.80, 0.50],
    [0.30, 0.40, 0.90]
])

print("Original 2D array:\n", probs_2d)

# Sort without specifying axis (default: axis = -1 → sort within each row)
print("\nSorted along last axis (axis=-1):\n", np.sort(probs_2d))

# Sort along rows (axis=0) — sorts *down* each column
print("\nSorted along axis=0 (down each column):\n", np.sort(probs_2d, axis=0))

# Sort along columns (axis=1) — sorts *across* each row
print("\nSorted along axis=1 (across each row):\n", np.sort(probs_2d, axis=1))


Original 2D array:
 [[0.65 0.15 0.2 ]
 [0.1  0.8  0.5 ]
 [0.3  0.4  0.9 ]]

Sorted along last axis (axis=-1):
 [[0.15 0.2  0.65]
 [0.1  0.5  0.8 ]
 [0.3  0.4  0.9 ]]

Sorted along axis=0 (down each column):
 [[0.1  0.15 0.2 ]
 [0.3  0.4  0.5 ]
 [0.65 0.8  0.9 ]]

Sorted along axis=1 (across each row):
 [[0.15 0.2  0.65]
 [0.1  0.5  0.8 ]
 [0.3  0.4  0.9 ]]


### `np.argsort()` – Get Sorted Indices

Returns the **indices** that would sort the array.
This is useful when you want the *ranking* or to reorder another array accordingly.

#### Example – Ranking model predictions

In [10]:
import numpy as np

# Probabilities for 3 classes
probs = np.array([0.65, 0.15, 0.20])

sorted_idx = np.argsort(probs)
print("Sorted indices:", sorted_idx)
print("Classes from lowest to highest probability:", sorted_idx)
print("Classes from highest to lowest probability:", sorted_idx[::-1])

Sorted indices: [1 2 0]
Classes from lowest to highest probability: [1 2 0]
Classes from highest to lowest probability: [0 2 1]


###  `np.unique()` – Find Unique Values

Finds all unique values in an array (optionally, also their counts or indices).
Useful for identifying **unique categories**, **class labels**, or **distinct values** in datasets.

#### Example – Unique class labels in dataset

In [11]:
labels = np.array(["cat", "dog", "dog", "cat", "bird", "dog"])

unique_labels = np.unique(labels)
print("Unique class labels:", unique_labels)

Unique class labels: ['bird' 'cat' 'dog']


### Summary

* **`np.sort`** get ordered values
* **`np.argsort`** get order indices (for ranking)
* **`np.unique`** get unique or categorical values

## Random Data Generation in NumPy

The `numpy.random` module provides functions for generating random numbers.
These are widely used for:

* Sampling data
* Initializing model weights
* Random shuffling
* Data augmentation

### Understanding the Random Seed

Every time you call a random function, NumPy uses an internal algorithm to produce random-looking numbers.
However, these numbers are **not truly random** — they’re **pseudo-random**, generated by a deterministic process.

The **random seed** is the *starting point* for this process.
If you set the same seed, NumPy will always produce the same random numbers.

Setting `np.random.seed(n)` makes your random results **reproducible** — crucial for experiments and debugging in machine learning.

In [ ]:
np.random.seed(42)
print("Run 1:", np.random.rand(3))

np.random.seed(42)
print("Run 2:", np.random.rand(3))

Run 1: [0.37454012 0.95071431 0.73199394]
Run 2: [0.37454012 0.95071431 0.73199394]


### Differences Between `rand`, `randint`, and `randn`

| Function                             | Description                                              | Output Range  |
| ------------------------------------ | -------------------------------------------------------- | ------------- |
| `np.random.rand(shape)`              | Uniform random floats                                    | [0, 1)        |
| `np.random.randint(low, high, size)` | Random integers                                          | [low, high) |
| `np.random.randn(shape)`             | Random floats from *normal distribution* (mean=0, std=1) | (-∞, +∞)      | 

In [13]:
np.random.seed(0)

print("rand:", np.random.rand(3))      # uniform
print("randint:", np.random.randint(0, 10, 3))  # integers
print("randint:", np.random.randint(0, 10, (3, 3)))  # integers
print("randn:", np.random.randn(3))    # normal distribution

rand: [0.5488135  0.71518937 0.60276338]
randint: [3 7 9]
randint: [[3 5 2]
 [4 7 6]
 [8 8 1]]
randn: [0.14404357 1.45427351 0.76103773]


# Advanced NumPy

## broadcasting

The term **broadcasting** describes how NumPy treats arrays with different shapes during arithmetic operations. Subject to certain constraints, the smaller array is “broadcast” across the larger array so that they have compatible shapes.

NumPy operations are usually done on pairs of arrays on an element-by-element basis. In the simplest case, the two arrays must have exactly the same shape, as in the following example:

In [14]:
a = np.array([1.0, 2.0, 3.0])
b = np.array([2.0, 2.0, 2.0])
a * b

array([2., 4., 6.])

NumPy’s broadcasting rule relaxes this constraint when the arrays’ shapes meet certain constraints. The simplest broadcasting example occurs when an array and a scalar value are combined in an operation:

In [15]:
a = np.array([1.0, 2.0, 3.0])
b = 2.0
a * b

array([2., 4., 6.])

The result matches the previous example where `b` was an array. Conceptually, `b` is stretched to match `a`'s shape, with copies of the scalar. However, NumPy optimizes this without creating actual copies, ensuring efficient memory and computation.

![Broadcasting](./Images/broadcasting.png)

### General broadcasting rules

When operating on two arrays, NumPy compares their shapes element-wise. It starts with the trailing (i.e. rightmost) dimension and works its way left. Two dimensions are compatible when

1. they are equal, or
2. one of them is 1.

Input arrays can have different dimensions. The result matches the array with the most dimensions, using the largest size per dimension, assuming missing dimensions are size one.

### Example 1

Scaling RGB values for an image

In [ ]:
image = np.random.rand(256, 256, 3)  # 256x256 image with 3 color channels
scale = np.array([0.5, 1.0, 1.5])  # Different scaling factors for each channel

# Broadcasting operation
scaled_image = image * scale

print("Image shape:", image.shape)
print("Scale shape:", scale.shape)
print("Result shape:", scaled_image.shape)

# Image shape:  (256, 256, 3)
# Scale shape:            (3,)
# Result shape: (256, 256, 3)

Image shape: (256, 256, 3)
Scale shape: (3,)
Result shape: (256, 256, 3)



### Example 2

Broadcasting with different shaped arrays

In [ ]:
A = np.random.rand(8, 1, 6, 1)  # 4D array
B = np.random.rand(   7, 1, 5)  # 3D array

# Broadcasting operation
result = A * B

print("A shape:", A.shape)
print("B shape:", B.shape)
print("Result shape:", result.shape)

# A shape:      (8, 1, 6, 1)
# B shape:         (7, 1, 5)
# Result shape: (8, 7, 6, 5)

A shape: (8, 1, 6, 1)
B shape: (7, 1, 5)
Result shape: (8, 7, 6, 5)


### Example 3

Examples of Arrays that can`t be broadcast.

In [18]:
try:
    A = np.random.rand(3)
    B = np.random.rand(4)
    result = A + B 
except ValueError as e:
    print(e)

operands could not be broadcast together with shapes (3,) (4,) 


In [19]:
try:
    A = np.random.rand(   2, 1)
    B = np.random.rand(8, 4, 3)
    result = A + B 
except ValueError as e:
    print(e)

operands could not be broadcast together with shapes (2,1) (8,4,3) 


### Example 4

Broadcasting when a 1-d array is added to a 2-d array

In [35]:
A = np.array([[ 0.0,  0.0,  0.0],
              [10.0, 10.0, 10.0],
              [20.0, 20.0, 20.0],
              [30.0, 30.0, 30.0]])
B = np.array([1.0, 2.0, 3.0])
A + B

array([[ 1.,  2.,  3.],
       [11., 12., 13.],
       [21., 22., 23.],
       [31., 32., 33.]])

![Broadcastin1D2D](./Images/broadcasting_2.png)

### Example 5

Broadcasting provides a convenient way of taking the outer product (or any other outer operation) of two arrays. The following example shows an outer addition operation of two 1-d arrays

In [21]:
a = np.array([0.0, 10.0, 20.0, 30.0])
b = np.array([1.0, 2.0, 3.0])
a[:, np.newaxis] + b

array([[ 1.,  2.,  3.],
       [11., 12., 13.],
       [21., 22., 23.],
       [31., 32., 33.]])

![Broadcasting](./Images/broadcasting_4.png)

Here the newaxis index operator inserts a new axis into a, making it a two-dimensional 4x1 array. Combining the 4x1 array with b, which has shape (3,), yields a 4x3 array.

## Structured arrays

Structured arrays are ndarrays whose datatype is a composition of simpler datatypes organized as a sequence of named fields. For example:

In [22]:
dt = np.dtype([('time', [('min', np.int64), ('sec', np.int64)]),
               ('temp', float)])
x = np.array([((10, 0), 2), ((10,30), 3), ((11,00), 5)], 
             dtype=dt)
x

array([((10,  0), 2.), ((10, 30), 3.), ((11,  0), 5.)],
      dtype=[('time', [('min', '<i8'), ('sec', '<i8')]), ('temp', '<f8')])

In [23]:
print(f'x[time]: {x["time"]}')

x[time]: [(10,  0) (10, 30) (11,  0)]


In [24]:
print(f'x[temp]: {x["temp"]}')

x[temp]: [2. 3. 5.]


### numpy.fromfile

Construct an array from data in a text or binary file.

In [25]:
import tempfile
fname = tempfile.mkstemp()[1]
x.tofile(fname)

In [26]:
np.fromfile(fname, dtype=dt)

array([((10,  0), 2.), ((10, 30), 3.), ((11,  0), 5.)],
      dtype=[('time', [('min', '<i8'), ('sec', '<i8')]), ('temp', '<f8')])

## Masked Arrays in NumPy

### Why Masked Arrays?

In real-world datasets, some values can be **missing** or **invalid**.
For example:

* A temperature sensor may fail and return `-999`.
* A survey might have unanswered fields.
* Some data could be corrupted or physically impossible.

The **`numpy.ma`** module helps handle such cases without removing or replacing values manually.
It lets you **“mask”** bad data — i.e., mark it as invalid so NumPy ignores it in computations.

### Basic Concept

A **masked array** combines:

* A **data array** (like any NumPy `ndarray`)
* A **mask**: Boolean array where

  * `True` → value is invalid (masked)
  * `False` → value is valid (used in computations)

Masked values are automatically excluded from calculations like `mean()`, `sum()`, `max()`, etc.

### Example 1

In [27]:
import numpy.ma as ma

# Example dataset: sensor readings
x = np.array([1, 2, 3, -1, 5])
print("Raw sensor readings:", x)

# Suppose -1 means an invalid measurement
mask = [0, 0, 0, 1, 0]  # mask=True (1) marks invalid entries

mx = ma.masked_array(x, mask=mask)
print("\nMasked array:\n", mx)
print("Mask:\n", mx.mask)

# Compute mean while ignoring invalid (masked) values
print("\nMean (ignoring masked values):", mx.mean())
print("Sum (ignoring masked values):", mx.sum())
print("Standard deviation (ignoring masked values):", mx.std())

Raw sensor readings: [ 1  2  3 -1  5]

Masked array:
 [1 2 3 -- 5]
Mask:
 [False False False  True False]

Mean (ignoring masked values): 2.75
Sum (ignoring masked values): 11
Standard deviation (ignoring masked values): 1.479019945774904


### Example 2 – Replacing Masked Values

You can “fill in” masked values with a constant (e.g., 0 or mean).

In [28]:
temps = np.array([20, 21, -999, 23, 22])
mtemps = ma.masked_equal(temps, -999)

print("Masked array:", mtemps)
print("Filled with 0:", mtemps.filled(0))
print("Filled with mean value:", mtemps.filled(mtemps.mean()))


Masked array: [20 21 -- 23 22]
Filled with 0: [20 21  0 23 22]
Filled with mean value: [20 21 21 23 22]


### Summary

| Function                    | Description                                 |
| --------------------------- | ------------------------------------------- |
| `ma.masked_equal(x, value)` | Mask all entries equal to a given value     |
| `ma.masked_where(cond, x)`  | Mask where condition is True                |
| `ma.masked_invalid(x)`      | Mask NaN or inf values                      |
| `ma.mean(x)`                | Mean ignoring masked values                 |
| `ma.sum(x)`                 | Sum ignoring masked values                  |
| `ma.filled(x, fill_value)`  | Replace masked values with given fill value |

## Stride Tricks

In [29]:
from numpy.lib import stride_tricks

### Reminder: Strides

#### What Are Strides?

In NumPy, **strides** show how many **bytes in memory** you need to move to reach the next element **along each axis**.

#### Example – 2D Array

In [30]:
x = np.array([[1, 2, 3],
              [4, 5, 6]])
print("Array:\n", x)
print("Shape:", x.shape)
print("Item size (bytes):", x.itemsize)
print("Strides:", x.strides)

Array:
 [[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Item size (bytes): 8
Strides: (24, 8)


#### Interpretation

Each element takes **8 bytes**.

* The second stride (8) → to move from one element to the next **in the same row**,
  NumPy jumps **8 bytes** in memory.
* The first stride (24) → to move to the next **row**, NumPy skips **24 bytes**
  (3 columns × 8 bytes = 24 bytes).

### numpy.lib.stride_tricks.sliding_window_view

The `numpy.lib.stride_tricks.sliding_window_view()` function creates sliding window views of N-dimensional arrays without copying data. This function is safer and easier to use than `as_strided()` for tasks like generating moving windows for convolution or analysis.

**Function Parameters**

| Parameter        | Description                                                  |
|------------------|--------------------------------------------------------------|
| `x`              | Input NumPy array                                            |
| `window_shape`   | Size of the sliding window (int or tuple for N-dim arrays)   |
| `axis` (optional) | Axis or axes to slide over; defaults to all axes            |

**Returns**

`view : ndarray`  
A new view of the input array with overlapping sliding windows.


#### Example 1D

In [31]:
x = np.arange(10)
print("x:", x)

windows = stride_tricks.sliding_window_view(x, window_shape=3)
print("Sliding window:\n", windows)

x: [0 1 2 3 4 5 6 7 8 9]
Sliding window:
 [[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


#### Example 2D

In [32]:
import numpy as np
from numpy.lib import stride_tricks

# Tworzymy macierz 2D
A = np.arange(1, 17).reshape(4, 4)
print("A:\n", A)

# Tworzymy okna 2x2
windows = stride_tricks.sliding_window_view(A, window_shape=(2, 2))
print("\nSliding 2x2 windows:\n", windows)

print("\nShape of windows:", windows.shape)


A:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

Sliding 2x2 windows:
 [[[[ 1  2]
   [ 5  6]]

  [[ 2  3]
   [ 6  7]]

  [[ 3  4]
   [ 7  8]]]


 [[[ 5  6]
   [ 9 10]]

  [[ 6  7]
   [10 11]]

  [[ 7  8]
   [11 12]]]


 [[[ 9 10]
   [13 14]]

  [[10 11]
   [14 15]]

  [[11 12]
   [15 16]]]]

Shape of windows: (3, 3, 2, 2)


For a 2D array `A` of shape (4,4), `sliding_window_view(A, (2,2))` produces a 4-D view of shape (3,3,2,2).  
The first two dimensions (3,3) represent the possible window positions,  
and the last two (2,2) are the shape of each window.  
Each element `windows[i,j]` is a 2×2 subarray `A[i:i+2, j:j+2]`.  
This is useful for vectorized convolution, pooling, or local neighborhood operations — all done without copying data.

### numpy.lib.stride_tricks.as_strided

The `numpy.lib.stride_tricks.as_strided()` function allows you to create custom views of NumPy arrays without copying data. It works by manipulating memory strides, enabling you to define a custom way of interpreting the underlying data.

**Function Parameters**

| Parameter     | Description                                           |
|---------------|-------------------------------------------------------|
| `x`           | Input NumPy array                                     |
| `shape`       | Desired shape of the new view                         |
| `strides`     | Bytes to move between elements in each dimension      |
| `subok`       | Keeps subclass type if `True` (default)               |
| `writeable`   | If `True`, allows changes to the view (use cautiously)|

**Returns**

`view : ndarray`
A new view of the input array with overlapping sliding windows.


**Risks**
1. **Memory violation risk** Manipulating strides allows reading data outside the valid array range, which can cause errors or undefined behavior.
2. **No data copying** Modifying elements of a view created with as_strided will also modify the original data.

#### Example
It can be used to efficiently perform operations on input data, such as creating sliding windows without memory overhead. This is particularly useful for convolutional operations.

In [ ]:
x = np.arange(10)

window_size = 3
stride = x.strides[0]

windows = stride_tricks.as_strided(x, 
                                   shape=(len(x) - window_size + 1, window_size), 
                                   strides=(stride, stride))
print(windows)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


**How It Works**

1. Create the input array x
2. Define the window size and stride
    * window_size = 3: We want overlapping sliding windows of length 3.
    * x.strides[0]: The stride for a 1D NumPy array is the number of bytes required to move from one element to the next.
3. Set the shape of the new view `shape=(len(x) - window_size + 1, window_size)`
    * len(x) = 10
    * We want windows of size 3, so the number of possible windows is 10 - 3 + 1 = 8. This makes the shape of the resulting array (8, 3).
4. Set the strides `strides=(stride, stride)`
    * The first value tells NumPy how many bytes to move when selecting the starting point of the next window (row).
    * The second value tells NumPy how many bytes to move between elements within a window (column).
