# Lista 3

## Numpy zaawansowane

(8pkt + 3pkt)

Na liście znajduje się 8 zadań do wykonania w trakcie zajęć. Po rozwiązaniu zadania pokaż kod prowadzącemu i odpowiedz na **pytanie kontrolne** — tylko wtedy przyznajemy punkty. Dodatkowo prześlij zadanie na platformie skos.

Jeśli w poleceniu nie jest wskazane użycie pętli `for` - nie korzystaj z niej.

Zadania dodatkowe są oznaczone ⭐️. To zadani o numerach 9, 10, 11 i 12. Punkty zostaną przyznane tylko za rozwiązania z 3 zadań. Rozwiąż te, które najbardziej Ci się podobają.

Każde zadnanie warte jest 1pkt.

## 1. Analiza fragmentów sygnału (slicing)

**Kontekst:**
Masz dane z czujnika EEG zapisane w tablicy `eeg_data` o wymiarach `(1000, 5, 3)` – 1000 próbek, dla 5 pacjentów, a każda próbka ma 3 kanały.
Chcesz przeanalizować wybrane fragmenty sygnału.

**Polecenie**

* Wybierz pierwsze 200 próbek – interesuje Cię początek nagrania.
* Wybierz tylko sygnał nr 1.
* Chcesz sprawdzić trend dla jednego z pacjentów. Dla pacjenta nr 3, z kanału nr 2 wybierz co piątą próbkę.
* Wybierz wyniki dla co 2 dnia i pacjentów o nieparzystych numerach.

**Podpowiedź**
Użyj slicingów `:`, `::`.

In [ ]:
import numpy as np

eeg_data = np.random.rand(1000, 5, 3)

# 1. pierwsze 200 próbek
part1 = eeg_data[:200, :, :]

# 2. tylko sygnał nr 1 (czyli kanał nr 0, zakładając indeksowanie od 0)
signal1 = eeg_data[:, :, 0]

# 3. dla pacjenta nr 3, kanał nr 2, co piąta próbka
trend_p3_ch2 = eeg_data[::5, 3, 2]

# 4. wyniki dla co 2 dnia i pacjentów o nieparzystych numerach (1, 3, 5 → czyli indeksy 0, 2, 4)
subset = eeg_data[::2, 1::2, :]

print("1. Pierwsze 200 próbek:", part1.shape)
print("2. Sygnał nr 1:", signal1.shape)
print("3. Trend pacjenta nr 3, kanał nr 2:", trend_p3_ch2.shape)
print("4. Co 2 dzień i nieparzyści pacjenci:", subset.shape)

1. Pierwsze 200 próbek: (200, 5, 3)
2. Sygnał nr 1: (1000, 5)
3. Trend pacjenta nr 3, kanał nr 2: (200,)
4. Co 2 dzień i nieparzyści pacjenci: (500, 2, 3)


## 2. Statystyki aktywności modelu (operacje po osiach)

**Kontekst:**
Masz dane `activations` o wymiarach `(3, 500)` – trzy neurony w warstwie modelu, zarejestrowane przez 500 kroków czasowych.
Chcesz zbadać ich zachowanie w czasie.

**Polecenie**

* Oblicz średnią aktywność każdego neuronu w czasie.
* Oblicz średnią aktywność w każdym kroku czasowym.
* Znajdź neuron o najwyższej średniej aktywności – który z trzech był najbardziej „aktywny”?

**Wskazówka:** Przydadzą się `np.mean()` i argument `axis`, oraz `np.argmax()`.

In [ ]:
activations = np.random.rand(3, 500)

# 1. średnia aktywność każdego neuronu
mean_per_neuron = np.mean(activations, axis=1)

# 2. średnia aktywność w każdym kroku czasowym
mean_per_step = np.mean(activations, axis=0)

# 3. neuron o najwyższej średniej aktywności
most_active_neuron = np.argmax(mean_per_neuron)

print("1. Średnia aktywność neuronów:", mean_per_neuron)
print("2. Średnia aktywność w krokach czasowych:", mean_per_step[:6])  # pokazujemy tylko kilka
print("3. Najbardziej aktywny neuron:", most_active_neuron)

1. Średnia aktywność neuronów: [0.47592624 0.50123349 0.49682914]
2. Średnia aktywność w krokach czasowych: [0.44580544 0.91353371 0.2146464  0.44449967 0.14961684 0.7357661 ]
3. Najbardziej aktywny neuron: 1


## 3. Podział szeregu czasowego (array_split)

**Kontekst:**
Chcesz przygotować dane do uczenia modelu, który trenuje się na krótszych fragmentach sygnału.

**Polecenie**

Masz daną tablicę `signal = np.arange(100)`. Uywając `np.array_split`:

* Podziel dane na 5 równych fragmentów (czyli po 20 próbek w każdym).
* Podziel dane tak, aby pierwszy zawierał próbki `[:30]`, drugi `[30:70]`, a trzeci `[70:]`.
* Podziel dane na dwie części, tak żeby pierwszy fragment zawierał próbki `[:60]`, a drugi `[60:]`.

In [ ]:
signal = np.arange(100)

# 1. 5 równych fragmentów
parts_equal = np.array_split(signal, 5)

# 2. podział wg konkretnych granic
parts_custom = np.array_split(signal, (30, 70,))

# 3. podział na dwie części ([:60], [60:])
parts_two = np.array_split(signal, (60,))

# wypisz rozmiary
print("1. 5 równych fragmentów:", [p.shape for p in parts_equal])
print("2. Podział [0:30], [30:70], [70:]:", [p.shape for p in parts_custom])
print("3. Podział [0:60], [60:]:", [p.shape for p in parts_two])

1. 5 równych fragmentów: [(20,), (20,), (20,), (20,), (20,)]
2. Podział [0:30], [30:70], [70:]: [(30,), (40,), (30,)]
3. Podział [0:60], [60:]: [(60,), (40,)]


## 4. Funkcje uniwersalne (ufuncs)

**Kontekst:**
Masz dane wejściowe `x` – 200 próbek w zakresie od -3 do 3.
Chcesz policzyć aktywacje typowe dla sieci neuronowych.

**Polecenie:**

* Wygeneruj `x = np.linspace(-3, 3, 200)`.
* Oblicz `sigmoid = 1 / (1 + exp(-x))`.
* Oblicz `relu = max(0, x)`.
* Porównaj średnie wartości tych funkcji.

In [ ]:
x = np.linspace(-3, 3, 200)

sigmoid = 1/(1+np.exp(-x))
relu = np.maximum(0, x)

print("Średnia sigmoid:", np.mean(sigmoid))
print("Średnia ReLU:", np.mean(relu))

Średnia sigmoid: 0.5
Średnia ReLU: 0.7537688442211055


## 5. Sortowanie i unikalne wartości

**Kontekst:**
Masz wektor `scores` z wynikami modelu klasyfikującego 100 obserwacji.
Chcesz zobaczyć, które próbki miały najwyższe wyniki i jakie unikalne klasy się pojawiły.

**Polecenie:**

* Wygeneruj losowe `scores` (np. `np.random.rand(100)`).
* Posortuj `scores` rosnąco.
* Zwróć **indeksy** sortowania (czyli w jakiej kolejności należy wziąć próbki).
* Wygeneruj losowy wektor `labels` z wartościami z zakresu `[0, 3]`.
* Wypisz unikalne etykiety i ich liczność.

**Podpowiedź:**
`np.sort`, `np.argsort`, `np.unique(..., return_counts=True)`

In [ ]:
# dane
scores = np.random.rand(100)
labels = np.random.randint(0, 4, size=100)

# sortowanie
sorted_scores = np.sort(scores)
sorted_idx = np.argsort(scores)

# unikalne wartości
unique_labels, counts = np.unique(labels, return_counts=True)

print("Posortowane wyniki:", sorted_scores[:5], "...")
print("Indeksy sortowania:", sorted_idx[:5])
print("Unikalne etykiety:", unique_labels)
print("Liczność:", counts)

Posortowane wyniki: [0.01092387 0.03106837 0.0411358  0.0426549  0.05152184] ...
Indeksy sortowania: [91 12 88 57 63]
Unikalne etykiety: [0 1 2 3]
Liczność: [21 31 24 24]


## 6. Łączenie i dzielenie tablic

**Kontekst:**
Masz dane z dwóch sensorów `sensor_A` i `sensor_B`, każdy po 100 próbek.
Chcesz stworzyć jedną tablicę cech oraz przetestować różne sposoby łączenia.

**Polecenie:**

* Wygeneruj dane `sensor_A` i `sensor_B` (np. `np.random.randn(100)`).
* Połącz dane wzdłuż nowej osi.
* Połącz dane wzdłuż istniejącej osi.
* Sprawdź wymiary obu wyników.

**Podpowiedź** `np.concatenate`, `np.stack`

In [ ]:
sensor_A = np.random.randn(100)
sensor_B = np.random.randn(100)

# łączenie po nowej osi (powstaje tablica 2 x 100)
stacked = np.stack((sensor_A, sensor_B))

# łączenie po istniejącej osi (powstaje wektor 200-elementowy)
concatenated = np.concatenate((sensor_A, sensor_B))

print("stacked shape:", stacked.shape)
print("concatenated shape:", concatenated.shape)

stacked shape: (2, 100)
concatenated shape: (200,)


## 7. Maski i filtrowanie danych (`numpy.ma`)

**Kontekst:**
Masz dane `loss_values` z treningu modelu (np. z 200 epok).
Chcesz sprawdzić, w których momentach **strata spadła poniżej 0.1**, i wygodnie pracować tylko z tymi fragmentami — używając **masked arrays** (`numpy.ma`), które pozwalają ukryć niechciane wartości bez ich usuwania z tablicy.

**Polecenie:**

* Ustaw random seed.
* Wygeneruj `loss_values` – malejący wykres strat (np. `np.linspace(1, 0, 200) + np.random.normal(0, 0.05, 200)`).
* Utwórz **masked array**, która ukryje wartości większe lub równe `0.1`.
* Wyświetl tylko wartości, które **nie są zamaskowane**.
* Policz, w ilu epokach model osiągnął niski błąd (`loss < 0.1`).
* Oblicz średnią z „dobrych” epok, ignorując zamaskowane dane.

**Podpowiedź:**

Użyj: `ma.masked_greater_equal`


In [ ]:
import numpy as np
import numpy.ma as ma

# dane

# Ustaw random seed
np.random.seed(0)
loss_values = np.linspace(1, 0, 200) + np.random.normal(0, 0.05, 200)

# tworzymy masked array – maskujemy wszystkie wartości >= 0.1
loss_masked = ma.masked_array(loss_values, mask = loss_values >= 0.1)
# loss_masked = ma.masked_greater_equal(loss_values, 0.1)   # shorter approach
odp = np.sum(loss_masked <0.1)
print(odp)
# wyświetlamy kilka niezamaskowanych wartości
print("Wartości z niskim błędem:", loss_masked.compressed()[:5])

# liczymy, ile epok miało stratę poniżej 0.1
n_low_loss = loss_masked.count()
print("Liczba epok z niskim błędem:", n_low_loss)

# obliczamy średnią tylko z niezamaskowanych danych
avg_low_loss = loss_masked.mean()
print("Średnia strata (dla niskich wartości):", round(avg_low_loss, 4))

23
Wartości z niskim błędem: [0.08356547 0.09810199 0.073916   0.07540741 0.07607527]
Liczba epok z niskim błędem: 23
Średnia strata (dla niskich wartości): 0.042


## 8. Stride tricks

**Kontekst:**
Podczas trenowania modeli w *computer vision* w celu optymalizacji złożoności modelu obrazy dzieli się na mniejsze fragmenty (np. do uczenia na patchach).

**Polecenie:**

Masz obraz o wymiarach **3 × 1000** (obraz czarno-biały o wymiarach 3x1000).

* Wygeneruj dane losowe (np. `np.random.rand(3, 1000)`).
* Użyj `numpy.lib.stride_tricks.sliding_window_view`, by stworzyć macierz okien, tak żeby obrazy nachodziły na siebie co 10 próbek.
* Sprawdź wymiary wynikowej tablicy. Ile masz okien?

**Podpowiedź:** Rozwiązanie powinno być postaci `sliding_window_view(image, window_shape=rozmiar_okna, axis=...)[::krok]`

In [ ]:
import numpy as np
from numpy.lib.stride_tricks import sliding_window_view

# dane wejściowe
image = np.random.rand(3, 1000)

# okna o długości 100 pikseli, przesuwane co 10
windows = sliding_window_view(image, window_shape=(100), axis=1)[:, ::10]

print("Wymiary wynikowej tablicy:", windows.shape)
print("Liczba okien:", windows.shape[1])

Wymiary wynikowej tablicy: (3, 91, 100)
Liczba okien: 91


## ⭐️ 9. Normalizacja niestandardowa

Utwórz `X` o wymiarach `(100, 10)` – 100 obserwacji, 10 cech o różnych zakresach, z zakresu [-100, 100].
Znormalizuj każdą kolumnę **do przedziału od min do max, ale tylko dla wartości dodatnich**.
Wartości ujemne mają pozostać niezmienione.

**Polecenie:**

* Wygeneruj dane `X` z rozkładu normalnego (`np.random.randn(100, 10)`).
* Utwórz maskę `mask = X > 0`.
* Zastosuj broadcastowanie, aby znormalizować każdą kolumnę:

  ```python
  X_norm = (X - X.min(axis=0)) / (X.max(axis=0) - X.min(axis=0))
  ```
* Nałóż maskę tak, aby wartości `≤ 0` w oryginale nie były zmieniane.

**Podpowiedź:**
Użyj `np.where`.

In [ ]:
import numpy as np
import numpy.ma as ma
x = (np.random.randn(100, 10)*200) - 100
mask = x < 0
x_norm = (x - x.min(axis=0)) / (x.max(axis=0) - x.min(axis=0))
np.where(mask, x_norm, x)

array([[1.94990938e+02, 1.45397086e-01, 5.35016164e-01, 3.61115010e-01,
        4.18425369e+02, 3.15688605e+02, 1.36012541e-02, 1.70122480e-01,
        1.06007645e+02, 2.98219625e+02],
       [2.55864202e-01, 4.61459417e-01, 4.71732238e-01, 2.08730932e+02,
        5.07360398e-01, 4.24923249e-01, 3.52041006e-01, 3.71864753e-01,
        2.08941768e+02, 3.45707572e-01],
       [1.67089031e-01, 4.09526352e-01, 2.35409358e+00, 4.39895320e+02,
        4.90366636e-01, 2.81194718e-01, 2.33862608e-01, 5.40689002e-01,
        2.84297377e-01, 5.03947966e-01],
       [5.91782545e-01, 5.15975058e-01, 1.64140361e+02, 2.00655064e-01,
        3.79590868e-01, 4.39846104e+01, 1.96339581e+02, 3.68331900e+02,
        1.43922700e+01, 9.03414218e+01],
       [5.56419748e-01, 9.61794607e+01, 3.98817909e-01, 2.85732843e-01,
        2.62235999e-01, 1.19442872e+02, 3.40824970e+01, 4.50450793e-01,
        2.25514399e+02, 1.59482203e+01],
       [1.32529766e+01, 3.87584980e+01, 1.74676472e+00, 1.73599282e+02,
   

## ⭐️ 10. Macierz odległości Euklidesowych w przestrzeni 1000D

Oblicz odległości pomiędzy punktami w bardzo wysokowymiarowej przestrzeni – np. przy analizie embeddingów w modelach językowych.

**Polecenie:**

* Wygeneruj **10 000 punktów w przestrzeni 1000-wymiarowej** (`np.random.rand(10_000, 1000)`).
* Używając **broadcastingu**, oblicz macierz odległości Euklidesowych między wszystkimi parami punktów.
* Zmierz czas wykonania tej operacji.
* Porównaj z implementacją opartą o trzy zagnieżdżone pętle (`for`).

‼ Jeśli twój kod dla 3 pętli będzie trwał dłużej niż 2min - przerwij i wypisz odpowiedni komunikat.

In [ ]:
import time
import numpy as np
from math import inf

def pairwise_distances_broadcast(x):
    # (x-y)^2 = x^2 + y^2 - 2 x.y
    sq = np.sum(x * x, axis=1, keepdims=True)  # (n,1)
    d2 = sq + sq.T - 2 * (x @ x.T)
    np.maximum(d2, 0, out=d2)
    return np.sqrt(d2)

def pairwise_distances_naive(x, timeout_s=120):
    n = x.shape[0]
    D = np.zeros((n, n), dtype=float)
    t0 = time.time()
    for i in range(n):
        for j in range(n):
            if time.time() - t0 > timeout_s:
                print(f"Computation longer than {timeout_s}s")
                return False
            D[i, j] = np.linalg.norm(x[i] - x[j])
    return D

def timed_large_run(n=10_000, d=1000):
    x = np.random.rand(n, d)

    t0 = time.time()
    D = pairwise_distances_broadcast(x)
    t_vec = time.time() - t0
    print(f"Vectorized computed in {t_vec:.3f}s")

    t0 = time.time()
    res = pairwise_distances_naive(x)
    t_naive = time.time() - t0
    if res != False: print(f"Naive computation finished in {t_naive:.3f}s")

timed_large_run(10000, 1000)

Vectorized computed in 5.148s
Computation longer than 120s


## ⭐️ 11. Stride tricks – zamiana kwadrantów tablicy

Stwórz dwuwymiarową tablicę. **Zamień miejscami górny prawy i dolny lewy kwadrant**, używając tylko `numpy` i `stride_tricks`, bez kopiowania danych.

**Polecenie:**

* Utwórz tablicę `A = np.arange(16).reshape(4, 4)` (dla prostoty).
* Za pomocą `stride_tricks` (np. `as_strided`) lub sprytnego indeksowania stwórz nowy widok tablicy. Twoje rozwiązanie powinno być postaci: `stride_tricks.as_strided(...).reshape(...)`

![task](./Images/ex_np_as_strided.png)


In [ ]:
import numpy.lib.stride_tricks as st
a = np.arange(16).reshape(4, 4)
print(a)
s0, s1 = a.strides
b = st.as_strided(a, shape=(2, 2, 2, 2), strides=(2*s0, s0, 2*s1, s1))
b = b.swapaxes(0, 2)
b = b.reshape(4, 4)
print(b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[ 0  1  8  9]
 [ 4  5 12 13]
 [ 2  3 10 11]
 [ 6  7 14 15]]


## ⭐️ 12. Maskowanie warunkowe w macierzach i analiza różnic

**Kontekst:**
Masz dwie macierze wyników modeli `A` i `B` `(1000, 10)`.
Chcesz policzyć różnice i średnie, **ignorując**:

* wszystkie pozycje, w których `A` lub `B` mają NaN,
* wartości ekstremalne (>95 percentyl każdej kolumny),
* wartości ujemne w obu macierzach **jednocześnie**.

**Polecenie:**

1. Wygeneruj `A` i `B` z losowego rozkładu i wprowadź kilka `NaN`.
2. Utwórz maskę, która jednocześnie:

   * maskuje NaN (`masked_invalid`),
   * maskuje wartości > 95 percentyl (`masked_greater`),
   * maskuje pozycje, gdzie `A < 0 & B < 0` (`masked_where` z `logical_and`).
3. Stwórz masked array, która będzie  `diff = |A-B|` z utworzoną powyżej maską.
4. Policz średnią i wariancję różnic macierzy `diff`, ignorując zamaskowane wartości.
5. Zastąp zamaskowane wartości średnią kolumnową.

**Podpowiedź**

Z biblioteki `numpy.ma` mogą się przydać:
`masked_invalid`, `masked_greater`, `masked_where`, `mask_or`, `mean`, `var`, `filled`.

Z biblioteki `numpy` przydadzą się: `np.percentile`, `np.logical_and`.

In [26]:
import numpy as np
import numpy.ma as ma

A = np.random.randn(1000, 10)
B = np.random.randn(1000, 10)

nan_idx = (np.random.rand(20) * A.size).astype(int)
A.flat[nan_idx[:10]] = np.nan
B.flat[nan_idx[10:]] = np.nan

print(A[:5])
print(B[:5])

masked_invalid = np.isnan(A) | np.isnan(B)
# masked_greater: for each column compute 95th percentile across combined values (ignoring NaNs)
# combined = np.vstack([A, B])
# percentiles95 = np.nanpercentile(combined, 95, axis=0)
# mask positions where either A or B exceed the 95th percentile for that column
masked_greater = (A > np.nanpercentile(A, 95, axis=0)) | (B > np.nanpercentile(B, 95, axis=0))

masked_where = (A < 0) & (B < 0)

mask = masked_invalid | masked_greater | masked_where


diff = np.abs(A - B)
diff_masked = ma.masked_array(diff, mask=mask)

print(diff_masked[:5])

mean_per_col = diff_masked.mean(axis=0)
var_per_col = diff_masked.var(axis=0)
mean_overall = diff_masked.mean()
var_overall = diff_masked.var()

print('\nMean per column:\n', mean_per_col)
print('\nVariance per column:\n', var_per_col)
print('\nOverall mean:', mean_overall)
print('Overall variance:', var_overall)

diff_filled = diff_masked.filled(mean_per_col)

print(diff_filled[:5])

[[ 0.57691611  1.07985617  0.33628909 -0.9042438  -0.63739352 -1.24081884
   0.58568946         nan -1.07481447 -1.19376905]
 [ 0.27252624  1.70979913  1.22318835 -0.18644607 -0.38868448 -1.14014092
   1.1001896   0.06982221 -0.81694819 -0.23817621]
 [-1.09903093  0.03630422 -1.04706573  0.52950694 -0.88299637  0.69883884
   0.09206958  0.21259193  0.20352694  0.45044807]
 [ 0.52383821 -0.47456271 -2.69721014 -1.21372197  0.89941107 -0.53337878
  -0.23300032  1.02178901  0.18320103 -0.12633551]
 [ 0.6309781  -0.92534002  0.19273476 -1.19835644  2.10068914 -0.61792542
  -0.72911567  1.51114854 -0.92171179 -1.3076607 ]]
[[-0.27078554  2.41963536  0.28593597  0.01652892 -1.74998427  0.36925135
   0.50310599 -0.16646489 -2.00565737 -0.76542784]
 [ 1.04346041 -0.63754119  0.28483652  0.07351333  0.84525535 -1.48762368
  -0.2486355   1.41211734  0.7177804  -0.74019776]
 [ 0.35458031 -0.52627247 -2.86001937 -1.91752115  0.44518193 -0.07624474
  -0.13145851  0.81502959  0.18313297 -0.08797563]