# Introduction to NumPy

## What is NumPy?

NumPy (Numerical Python) is a fundamental library for scientific computing in Python.  
It provides:
- a powerful **n-dimensional array object** (`ndarray`),
- tools for **mathematical and logical operations**,
- fast routines for **linear algebra, statistics, random generation**, and more.

### NumPy Arrays (`ndarray`)

A **NumPy array** (also called an `ndarray`) is a **multidimensional, homogeneous data structure** provided by the NumPy library in Python. It is designed for efficient numerical and scientific computing.

Unlike Python lists, NumPy arrays store elements of the **same data type** and allow **vectorized operations**, meaning operations are applied to entire arrays without explicit loops.

**Key features:**

* Homogeneous elements (same data type)
* Multidimensional (1D, 2D, or more)
* Efficient (C-based implementation)
* Supports broadcasting and element-wise operations

### NumPy Arrays (`ndarray`) vs Python Lists

| Feature | Python List | NumPy ndarray |
|----------|--------------|----------------|
| Size | Dynamic | Fixed at creation |
| Data types | Mixed allowed | All elements must have the same type |
| Memory layout | Objects stored separately | Contiguous memory block (efficient) |
| Performance | Slower (interpreted Python) | Much faster (C-optimized) |
| Supported operations | Basic | Vectorized math, broadcasting, etc. |


### Example: Speed Comparison

In [1]:
import numpy as np
import time

N = 10000000
a_list = list(range(N))
b_list = list(range(N))
a_np = np.arange(N)
b_np = np.arange(N)

# Python loop
start = time.time()
c_list = [a_list[i] * b_list[i] for i in range(N)]
print("Python list time:", time.time() - start, "seconds")

# NumPy operation
start = time.time()
c_np = a_np * b_np
print("NumPy array time:", time.time() - start, "seconds")

Python list time: 0.23435616493225098 seconds
NumPy array time: 0.008805036544799805 seconds


## Array Creation in NumPy

NumPy provides several convenient ways to create arrays.  
You can build them from Python lists, generate them with built-in functions, or fill them with specific values.


### Creating arrays from Python lists or tuples

Use `np.array()` to convert a regular Python list or tuple into a NumPy array.

In [2]:
a = np.array([2, 3, 4])
print(a)
print(a.dtype)

b = np.array([1.2, 3.5, 5.0])
print(b.dtype)

[2 3 4]
int64
float64


NumPy automatically infers the element type from the data you provide.

### Creating multi-dimensional arrays

You can nest sequences (lists or tuples) to create higher-dimensional arrays.

In [3]:
b = np.array([[1.5, 2, 3], [4, 5, 6]])
print(b)

[[1.5 2.  3. ]
 [4.  5.  6. ]]


### Specifying the data type

You can set the element type using the `dtype` keyword.

In [4]:
c = np.array([[1, 2], [3, 4]], dtype=complex)
print(c)

[[1.+0.j 2.+0.j]
 [3.+0.j 4.+0.j]]


### Creating placeholder arrays

When the array size is known but the contents are not, NumPy provides fast constructors:

| Function          | Description                                                      | 
| ----------------- | ---------------------------------------------------------------- |
| `np.zeros(shape)` | Creates an array filled with zeros                               |
| `np.ones(shape)`  | Creates an array filled with ones                                |
| `np.empty(shape)` | Creates an uninitialized array (contents depend on memory state) |

In [5]:
print(f'np.zeros((3, 4)): \n {np.zeros((3, 4))}\n')
print(f'np.ones((2, 3, 4): \n {np.ones((2, 3, 4))}\n')
print(f'np.empty((2, 3)): \n {np.empty((2, 3))}\n') # unpredictable values

np.zeros((3, 4)): 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

np.ones((2, 3, 4): 
 [[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]

np.empty((2, 3)): 
 [[1.5 2.  3. ]
 [4.  5.  6. ]]



### Creating numeric sequences

#### Using `np.arange()`

Similar to Python’s built-in `range()`, but returns an array instead of a list.

In [6]:
x = np.arange(10, 30, 5)
print(x)

x = np.arange(0, 2, 0.3)
print(x)

[10 15 20 25]
[0.  0.3 0.6 0.9 1.2 1.5 1.8]


⚠️ When using floating-point steps, the endpoint and number of elements may not be exact due to rounding errors.

#### Using `np.linspace()`

`linspace()` lets you specify **how many values** you want, not the step size.
This is usually more precise for evenly spaced sequences.

In [7]:
from numpy import pi

x = np.linspace(0, 2 * pi, 5)
print(x)

[0.         1.57079633 3.14159265 4.71238898 6.28318531]


### Summary

| Function                                | Purpose                                                   | Example                |
| --------------------------------------- | --------------------------------------------------------- | ---------------------- |
| `np.array()`                            | Create from list or tuple                                 | `np.array([1, 2, 3])`  |
| `np.zeros()`, `np.ones()`, `np.empty()` | Create placeholder arrays                                 | `np.zeros((3, 4))`     |
| `np.arange()`                           | Create numeric sequence with a fixed step                 | `np.arange(0, 10, 2)`  |
| `np.linspace()`                         | Create evenly spaced sequence with fixed number of points | `np.linspace(0, 1, 5)` |

## Internal Organization of NumPy Arrays

A NumPy array consists of **two main parts**:
1. the **data buffer** – the raw block of memory where the actual numbers are stored, and  
2. the **metadata** – information that tells NumPy how to interpret that memory.

This design allows NumPy to handle large datasets efficiently and perform operations without unnecessary copying.

### What the metadata contains

- `ndarray.itemsize`
The **size in bytes** of one element.  
Equivalent to `ndarray.dtype.itemsize`.

- `ndarray.ndim` number of dimensions (axes) of the array.  

- `ndarray.shape` a tuple indicating the size of each dimension, e.g. `(rows, columns)`.

- `ndarray.dtype` Describes the **data type** of each element. It can represent basic types (`int32`, `float64`) or compound types.

- `ndarray.strides`
A tuple indicating **how many bytes** to skip in memory to move to the next element along each axis.

- `ndarray.flags`
Contains information such as:
  * whether the array is **read-only**,  
  * if it’s **C-contiguous** or **Fortran-contiguous** in memory,  
  * and other internal memory layout details.

In [8]:
arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]], dtype=np.int32)

print("Array:\n", arr)
print("-" * 40)

print("arr.itemsize:", arr.itemsize)
print("arr.ndim:", arr.ndim)
print("arr.shape:", arr.shape)
print("arr.dtype:", arr.dtype)
print("arr.strides:", arr.strides)
print("arr.flags:\n", arr.flags)


Array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
----------------------------------------
arr.itemsize: 4
arr.ndim: 2
arr.shape: (3, 4)
arr.dtype: int32
arr.strides: (16, 4)
arr.flags:
   C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False



### Example: Changing shape

The shape of the array can be changed very easily without changing anything in the data buffer or any data copying at all. To reshape the array in-place assume a tuple of array dimensions to it. Reshaping an array in-place will fail if a copy is required.

In [9]:
x = np.arange(0, 24).reshape((2, 3, 4))
print(f'x.shape: {x.shape}')
print(f'x.strides: {x.strides}')
print(x)

x.shape: (2, 3, 4)
x.strides: (96, 32, 8)
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [10]:
x.shape = (3, 8)
print(f'x.shape: {x.shape}')
print(f'x.strides: {x.strides}')
print(x)

x.shape: (3, 8)
x.strides: (64, 8)
[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23]]


In [11]:
# # ValueError: total size of new array must be unchanged
# x.shape = (3, 6)

In [12]:
# # AttributeError: Incompatible shape for in-place modification. Use `.reshape()` to make a copy with the desired shape.
# np.zeros((4,2))[::2].shape = (-1,)

## Memory

The actual data of a numpy array is stored in a homogeneous and contiguous block of memory called data buffer. 

![Memory](./Images/PythonMemory.png)

### Strides
Stride is a tuple of bytes to step in each dimension when traversing an array.

In [13]:
y = np.reshape(np.arange(2*3*4), (2,3,4))
y

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [14]:
y.strides

(96, 32, 8)

In [15]:
z = y.T
z.strides

(8, 32, 96)

In [16]:
y[1,1,1]

17

At this step, we want to calculate how many bytes we need to "jump" in memory to access the element.

In [17]:
offset=sum(y.strides * np.array((1,1,1)))
offset/y.itemsize

# Simpler:
# i0, i1, i2 = 1, 1, 1
# offset_bytes = y.strides[0] * i0 + y.strides[1] * i1 + y.strides[2] * i2

17.0

What does `y.strides * np.array((1, 1, 1))` mean?

Each dimension of the array (2, 3, 4) has its own stride, which tells us how far apart elements are in memory:
* For the first dimension (axis 0), we need to jump 96 bytes to move to the next element.
* For the second dimension (axis 1), we jump 32 bytes.
* For the third dimension (axis 2), we jump 8 bytes.

By summing these values we obtain the offset.

What about `offset / y.itemsize`?

Each element occupies 4 bytes (y.itemsize == 4). To find the position of the element in the flattened 1D representation, we divide `offset / y.itemsize`.

## Basic Operations with NumPy Arrays

NumPy arrays support **elementwise arithmetic operations**, meaning operations are applied to each element individually. A new array is usually created with the result.

In [18]:
import numpy as np
from numpy import pi

a = np.array([20, 30, 40, 50])
b = np.arange(4)  # [0, 1, 2, 3]

c = a - b
print(c)  
print(b**2)
print(10 * np.sin(a))
print(a < 35)

[20 29 38 47]
[0 1 4 9]
[ 9.12945251 -9.88031624  7.4511316  -2.62374854]
[ True  True False False]


### Elementwise vs. Matrix Multiplication

In NumPy, the `*` operator performs **elementwise multiplication**.
For matrix multiplication, use `@` (Python ≥3.5) or the `dot()` method.

In [19]:
A = np.array([[1, 1],
              [0, 1]])
B = np.array([[2, 0],
              [3, 4]])

print('Elementwise product:')
print(A * B)

print('Matrix product:')
print(A @ B)
print(A.dot(B))

Elementwise product:
[[2 0]
 [0 4]]
Matrix product:
[[5 4]
 [3 4]]
[[5 4]
 [3 4]]


### In-place Operations

Some operations, like `+=` and `*=`, **modify the array directly** instead of creating a new one.

In [20]:
a = np.ones((2, 3), dtype=int) # Why dtype=int?
b = np.random.randint(0, 10, (2, 3))

print(f'a:\n{a}')
print(f'b:\n{b}')

a *= 3
print(f'a *= 3:\n{a}')
b += a
print(f'b += a:\n{b}')

a:
[[1 1 1]
 [1 1 1]]
b:
[[6 3 7]
 [5 6 1]]
a *= 3:
[[3 3 3]
 [3 3 3]]
b += a:
[[ 9  6 10]
 [ 8  9  4]]


### Type Promotion (Upcasting)

When arrays of different types are combined, NumPy **upcasts** to the more general type.

In [21]:
a = np.ones(3, dtype=np.int32)
b = np.linspace(0, pi, 3)

print(f'a.dtype: {a.dtype}')
print(f'b.dtype: {b.dtype}')

c = a + b
print(f'c = a + b, c : {c}')
print(f'c.dtype: {c.dtype}')

d = np.exp(c * 1j)
print(f'd: {d}')
print(f'd.dtype: {d.dtype}')

a.dtype: int32
b.dtype: float64
c = a + b, c : [1.         2.57079633 4.14159265]
c.dtype: float64
d: [ 0.54030231+0.84147098j -0.84147098+0.54030231j -0.54030231-0.84147098j]
d.dtype: complex128


### Unary Operations

NumPy arrays have built-in **methods for common operations**, such as sum, min, max.

In [22]:
a = np.random.randint(0,100, (2, 3))
print(a)

print(a.sum())
print(a.min())
print(a.max())

[[37 98 24]
 [79 36 60]]
334
24
98


### Operations Along an Axis

By default, methods treat the array as a flat list.
Use the `axis` parameter to operate along a specific dimension.

In [23]:
b = np.arange(12).reshape(3, 4)
print(f'b:\n{b}')

# Sum of each column
print(f'sum:\n{b.sum(axis=0)}')

# Min of each row
print(f'min:\n{b.min(axis=1)}')

# Cumulative sum along each row
print(f'cumsum:\n{b.cumsum(axis=1)}')

b:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
sum:
[12 15 18 21]
min:
[0 4 8]
cumsum:
[[ 0  1  3  6]
 [ 4  9 15 22]
 [ 8 17 27 38]]


### Summary

| Operation                       | Description                                                         |
| ------------------------------- | ------------------------------------------------------------------- |
| `+ - * / **`                    | Elementwise arithmetic                                              |
| `@` or `dot()`                  | Matrix multiplication                                               |
| `+=, *=`                        | In-place modification                                               |
| `sum(), min(), max(), cumsum()` | Unary array operations                                              |
| `axis` parameter                | Perform operation along rows (`axis=1`) or columns (`axis=0`)       |
| Type promotion                  | Operations between different dtypes result in the more general type |

## Indexing, Slicing, and Iterating in NumPy

NumPy arrays can be **indexed, sliced, and iterated** over, similar to Python lists, but with additional features for multidimensional arrays.

### One-dimensional arrays

In [24]:
import numpy as np

a = np.arange(10)**3

print("Full array a:")
print(a)  # [0 1 8 27 64 125 216 343 512 729]


# Indexing
print("\nElement at index 2 (a[2]):")
print(a[2])  # 8


# Slicing
print("\nSlice from index 2 to 5 (a[2:5]):")
print(a[2:5])  # [8 27 64]


# Assigning to slices
print("\nAssigning 1000 to every 2nd element up to position 6 (a[:6:2] = 1000):")
a[:6:2] = 1000 # a[start:stop:step]
print("Array after assignment:")
print(a)  # [1000, 1, 1000, 27, 1000, 125, 216, 343, 512, 729]


# Reversing
print("\nArray reversed (a[::-1]):")
print(a[::-1])  # reversed order


# Iterating
print("\nIterating over a and printing each element’s cube root:")
for i in a:
    print(i**(1/3))


Full array a:
[  0   1   8  27  64 125 216 343 512 729]

Element at index 2 (a[2]):
8

Slice from index 2 to 5 (a[2:5]):
[ 8 27 64]

Assigning 1000 to every 2nd element up to position 6 (a[:6:2] = 1000):
Array after assignment:
[1000    1 1000   27 1000  125  216  343  512  729]

Array reversed (a[::-1]):
[ 729  512  343  216  125 1000   27 1000    1 1000]

Iterating over a and printing each element’s cube root:
9.999999999999998
1.0
9.999999999999998
3.0
9.999999999999998
4.999999999999999
5.999999999999999
6.999999999999999
7.999999999999999
8.999999999999998


### Multidimensional arrays

Each axis of a multidimensional array can be indexed individually.

In [25]:
import numpy as np

def f(x, y):
    return 10*x + y

b = np.fromfunction(f, (5, 4), dtype=int)

print("Full array b (5x4):")
print(b)

print("\nElement at row 2, column 3 (b[2, 3]):")
print(b[2, 3])


print("\nColumn 1, rows 0 to 4 (b[0:5, 1]):")
print(b[0:5, 1])


print("\nColumn 1 using ':' to select all rows (b[:, 1]):")
print(b[:, 1])


print("\nRows 1 to 2, all columns (b[1:3, :]):")
print(b[1:3, :])

Full array b (5x4):
[[ 0  1  2  3]
 [10 11 12 13]
 [20 21 22 23]
 [30 31 32 33]
 [40 41 42 43]]

Element at row 2, column 3 (b[2, 3]):
23

Column 1, rows 0 to 4 (b[0:5, 1]):
[ 1 11 21 31 41]

Column 1 using ':' to select all rows (b[:, 1]):
[ 1 11 21 31 41]

Rows 1 to 2, all columns (b[1:3, :]):
[[10 11 12 13]
 [20 21 22 23]]


### Using ellipsis `...`

Ellipsis represents as many `:` slices as needed:

In [26]:
c = np.array([[[0, 1, 2],
               [10, 12, 13]],
              [[100, 101, 102],
               [110, 112, 113]]])
print(c.shape)
print(c[1, ...])
print(c[..., 2])

(2, 2, 3)
[[100 101 102]
 [110 112 113]]
[[  2  13]
 [102 113]]


### Iterating over arrays

Iteration happens along the **first axis** by default:

In [27]:
for row in b:
    print(row)

[0 1 2 3]
[10 11 12 13]
[20 21 22 23]
[30 31 32 33]
[40 41 42 43]


To iterate over **all elements** of an array, use the `flat` attribute:


In [28]:
for element in b.flat:
    print(element)

0
1
2
3
10
11
12
13
20
21
22
23
30
31
32
33
40
41
42
43



### Summary

| Concept                            | Description                                                       |
| ---------------------------------- | ----------------------------------------------------------------- |
| `array[i]`                         | Indexing along first axis (or specified axis for multidim arrays) |
| `array[start:stop:step]`           | Slicing with optional step                                        |
| `array[:, col]` or `array[row, :]` | Slice specific columns or rows                                    |
| `array[...]`                       | Ellipsis: fill in missing slices                                  |
| Iterating                          | Default along first axis; `flat` iterates over all elements       |

## Shape Manipulation in NumPy

NumPy provides multiple ways to **change the shape of arrays**, stack arrays together, and split them.

### Understanding the shape of an array

In [29]:
import numpy as np

a = np.floor(10 * np.random.randint(0, 100, (3, 4)))
print(a)
print(a.shape)

[[430. 990. 410. 340.]
 [960.  80. 100. 840.]
 [190. 810.  20. 710.]]
(3, 4)


### Changing the shape

#### Flattening, reshaping, and transposing


In [30]:
import numpy as np

a = np.arange(12).reshape(3, 4)
print("Original array a (3x4):")
print(a)


# Flatten the array into 1D
print("\nFlattened array using ravel():")
print(a.ravel())

# Reshape into 6x2 (returns a new array)
print("\nReshaped array into shape (6, 2) using reshape():")
print(a.reshape(6, 2))

# Transpose the array
print("\nTransposed array (swap rows and columns) using a.T:")
print(a.T)

print("\nShape of the transposed array:")
print(a.T.shape)

# Original array remains unchanged
print("\nShape of the original array (a) remains the same:")
print(a.shape)

Original array a (3x4):
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

Flattened array using ravel():
[ 0  1  2  3  4  5  6  7  8  9 10 11]

Reshaped array into shape (6, 2) using reshape():
[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]]

Transposed array (swap rows and columns) using a.T:
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]

Shape of the transposed array:
(4, 3)

Shape of the original array (a) remains the same:
(3, 4)


#### Resizing in-place

In [31]:
a.resize((2, 6))
print(a)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]


#### Using `-1` to infer dimension

In NumPy, the -1 in the reshape() method is a special placeholder that tells NumPy to automatically calculate the dimension so that the total number of elements remains the same.
You can only use one -1 per reshape().

In [32]:
a = np.random.randint(0, 100, (3, 4))
print(a.reshape(3, -1))

[[83  4 32 79]
 [51 19 56 91]
 [14 79 19  7]]


#### Stacking arrays

You can combine arrays along different axes.

In [33]:
a = np.random.randint(0, 100, (2, 2))
b = np.random.randint(0, 100, (2, 2))

print(f'a:\n{a}')
print(f'b:\n{b}')

# Vertical stack
print("Vertical stack:")
print(np.vstack((a, b)))

# Horizontal stack
print("Horizontal stack:")
print(np.hstack((a, b)))

a:
[[93 43]
 [93 69]]
b:
[[87 49]
 [35 83]]
Vertical stack:
[[93 43]
 [93 69]
 [87 49]
 [35 83]]
Horizontal stack:
[[93 43 87 49]
 [93 69 35 83]]


> **Note:** `hstack` concatenates along the second axis, `vstack` along the first axis. For higher dimensions, `concatenate` allows specifying the axis.

#### Column stack (for 1D arrays or 2D arrays as columns)

Stack 1-D arrays as columns into a 2-D array.

Take a sequence of 1-D arrays and stack them as columns to make a single 2-D array. 2-D arrays are stacked as-is, just like with hstack. 1-D arrays are turned into 2-D columns first.

In [34]:
from numpy import newaxis

a = np.array([4., 2.])
b = np.array([3., 8.])

print(f'a:\n{a}')
print(f'b:\n{b}')

print("Column stack:")
print(np.column_stack((a, b)))

print("Column stack with newaxis:")
print(np.column_stack((a[:, newaxis], b[:, newaxis])))

a:
[4. 2.]
b:
[3. 8.]
Column stack:
[[4. 3.]
 [2. 8.]]
Column stack with newaxis:
[[4. 3.]
 [2. 8.]]


## Splitting arrays

### Horizontal split

Split an array into multiple sub-arrays horizontally (column-wise).

In [35]:
a = np.random.randint(0, 10, (2, 6))

print(np.hsplit(a, 3))  # split into 3 equal parts
print(np.hsplit(a, (3, 4)))  # split after 3rd and 4th column

[array([[3, 7],
       [2, 4]]), array([[9, 9],
       [8, 1]]), array([[3, 5],
       [3, 3]])]
[array([[3, 7, 9],
       [2, 4, 8]]), array([[9],
       [1]]), array([[3, 5],
       [3, 3]])]


### Vertical split

Split an array into multiple sub-arrays vertically (row-wise).

In [36]:
np.vsplit(a, 2)  # split along first axis

[array([[3, 7, 9, 9, 3, 5]]), array([[2, 4, 8, 1, 3, 3]])]

### Flexible split

In [37]:
np.array_split(a, 3, axis=1)  # specify axis

[array([[3, 7],
        [2, 4]]),
 array([[9, 9],
        [8, 1]]),
 array([[3, 5],
        [3, 3]])]

### Summary

| Operation                                         | Description                                |
| ------------------------------------------------- | ------------------------------------------ |
| `reshape`, `resize`, `ravel`, `T`                 | Change the shape of an array or flatten it |
| `-1` in reshape                                   | Automatically calculate the dimension      |
| `hstack`, `vstack`, `column_stack`, `concatenate` | Stack arrays along different axes          |
| `hsplit`, `vsplit`, `array_split`                 | Split arrays horizontally or vertically    |

## Copies and Views in NumPy and Copy library

When working with NumPy arrays, **sometimes data is copied, sometimes not**. This is a common source of confusion for beginners. There are **three main cases**:

### No Copy at All

Simple assignments do **not create a copy**. Both variables point to the same array.

In [38]:
import numpy as np

a = np.array([[ 0,  1,  2,  3],
              [ 4,  5,  6,  7],
              [ 8,  9, 10, 11]])

b = a             # no new object is created
print(b is a)     # True, both names refer to the same ndarray

True


Passing mutable objects to functions also does not make a copy:

In [39]:
def f(x):
    print(id(x))  # unique object identifier

print(id(a))
f(a)
# Both outputs will be the same

4490638992
4490638992


### View (Shallow Copy)

A **view** is a new array object that looks at the same data.

In [40]:
c = a.view()
print(c is a)         # False, different objects
print(c.base is a)    # True, shares data with 'a'
print(c.flags.owndata) # False

False
True
False


Modifying the view **affects the original array**:

In [41]:
c = c.reshape((2, 6))
print(a.shape)  # (3, 4) - a's shape doesn't change

c[0, 4] = 1234
print(a)

(3, 4)
[[   0    1    2    3]
 [1234    5    6    7]
 [   8    9   10   11]]


Slicing returns a view:

In [42]:
s = a[:, 1:3]
s[:] = 10
print(a)
print(c)

[[   0   10   10    3]
 [1234   10   10    7]
 [   8   10   10   11]]
[[   0   10   10    3 1234   10]
 [  10    7    8   10   10   11]]


> Difference: `s = 10` reassigns the variable, while `s[:] = 10` modifies the underlying data.

### Deep Copy

The **copy** method creates a **new array with new data**.

In [43]:
d = a.copy()
print(d is a)       # False
print(d.base is a)  # False

d[0, 0] = 9999
print(a)

False
False
[[   0   10   10    3]
 [1234   10   10    7]
 [   8   10   10   11]]


Deep copies are useful when working with **large arrays** and slicing only a small portion:

In [44]:
a = np.arange(int(1e8))
b = a[:100].copy()  # deep copy of a small slice
del a                # memory of 'a' can now be released

> ⚠️ If `b = a[:100]` is used instead, `b` still references `a` and the memory cannot be released even after `del a`.


### Copy library 

Lets compare np.copy() and np.view() with copy.deepcopy(), copy.copy().
Shallow copy creates a new object that references the same inner objects as the original, sharing data references. Changes to inner objects affect all references, but changes to top-level objects may not.

When you change the inner item (origin[1][0]), all collections reflect the change:
from copy import copy

In [45]:
from copy import copy

# changing inner item
origin = [[1], [2], [3]]
shallow_copy = copy(origin)
referenced = origin
origin[1][0] = 0

print(origin)     
print(shallow_copy) 
print(referenced) 

[[1], [0], [3]]
[[1], [0], [3]]
[[1], [0], [3]]


When you change a top-level item (origin[1]), the reference reflects the change, but the shallow copy remains unchanged because it shares references to the inner lists:

In [46]:
# changing a top-level item
origin = [[1], [2], [3]]
shallow_copy = copy(origin)
referenced = origin
origin[1] = 0

print(origin)      
print(shallow_copy) 
print(referenced)  

[[1], 0, [3]]
[[1], [2], [3]]
[[1], 0, [3]]


Deep copy duplicates the entire structure, including all nested sublists, ensuring independence:
from copy import deepcopy

In [47]:
from copy import deepcopy 

origin = [[1],[2],[3]]
deep_copy = deepcopy(origin)
referenced = origin
origin[1][0]= 0

print(origin) 
print(deep_copy) 
print(referenced) 

[[1], [0], [3]]
[[1], [2], [3]]
[[1], [0], [3]]


### Summary

Here’s the key difference between references, shallow copies, and deep copies:
- `copy.deepcopy()` → Creates a completely independent copy of an object, including all nested elements. Changes in the original object do not affect the deep copy.
- `References` → Simply point to the same object, meaning any modification to the original will be reflected in all references.
- `copy.copy()` → Creates a shallow copy, duplicating only the outer structure of an object, but the inner elements remain shared with the original.
- `np.copy()` → In NumPy, this creates a fully independent copy of an array, duplicating all data.
- `np.view()` → Creates a new view of the same data, meaning changes in one will affect the other.

In NumPy:

| Concept            | Description                                               |
| ------------------ | --------------------------------------------------------- |
| Assignment `b = a` | No copy, both names refer to the same array               |
| `view()`           | Shallow copy, new array object, shares data with original |
| Slicing            | Returns a view (shares data)                              |
| `copy()`           | Deep copy, creates a new array with independent data      |
